<?php
define('HEADING_TITLE','ShipWire World Class Fullfillment Services');
define('CONTENT_TEXT1','<div ALIGN="center"><table BORDER="0" CELLPADDING="0" STYLE="border-collapse: collapse" WIDTH="100%" ID="table1"><tr><td style="padding-right:20px"><FONT face="arial, helvetica, sans-serif"><table border="0" width="100%" id="table744" cellspacing="0" cellpadding="0"><tr><td width="630" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002">' .
                                    '<span class="main"><b>Receive, store, and ship merchandise right from CRE Loaded!</b></span><br><span class="smallText">100% integrated with your CRE Loaded application, our Shipwire module sends orders from CRE Loaded directly to your Shipwire fulfillment center. Take advantage of Shipwire’s volume discounts and have your orders automatically packaged and shipped, often for less than the cost of standard shipping.</span>' . 
                                    '<p><span class="main"><b>What is Shipwire?</b></span><br><span class="smallText">Shipwire is a popular order fulfillment service that allows you to store merchandise in massive Chicago and Los Angeles warehouses. Then as each order comes into your online store, Shipwire will pack and ship it for you.</p>' . 
                                    '<p><span class="smallText">You can add a Shipwire account with just a few clicks of the mouse - no programming involved. If you\'re just starting out, or looking for a better way to manage your shipping and handling, Shipwire offers an easy and quick way to outsource shipping with no startup, receiving, storage or packaging fees. You just pay $79.95 a month, plus a Shipwire handling fee on the merchandise that they ship. Handling fees range from $1 to $1.50 an item and depend on the type of handling your product needs. </span></p>' . 
                                    '<p><span class="smallText">With Shipwire, your customers can receive merchandise anywhere in the world, serviced by the USPS, UPS or one of our freight partners. With facilities shipping more than 200,000 orders a month, they can customize your merchandise with assembly and kitting services at extremely affordable prices.</span></p>' .
                                    '<p><span class="smallText">Shipwire makes it simple to automate order fulfillment on your site: Get approved in 24 hours. As soon as you enter your SKU information and send them your initial inventory, they can start shipping your orders.</span></p>' . 
                                    '<p><span class="smallText">Shipwire makes extensive efforts to help you accurately monitor shipping and handling costs. Shipwire\'s reporting tools help you understand your inbound and outbound shipping, and automate time-consuming bookkeeping tasks.</span></p>');

define('CONTENT_TEXT2','<span class="smallText"><p>Check out our <a TARGET="_blank" HREF="http://www.creloaded.com/pages.php?CDpath=68_84_145"><b>Shipwire Pro Checkout Success Module</b></a>, which allows you to manage mixed orders; send only those products you choose via Shipwire from a successful order.</span>' .
                                     '<br>&nbsp;</p></td><td width="30" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002">&nbsp;</td><td valign="top" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><FONT face="arial, helvetica, sans-serif" size="2"><span style="font-size:13px;font-family:Arial; color:#000002">' . 
                                     '<span class="lb08"><img src="images/pixel_trans.gif" width="20" height="30" /><table border="0" cellpadding="0" cellspacing="0" id="table745" width="190"><tr style="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><td width="1" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="1" height="1" alt=""></td>' .
                                     '<td width="5" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="5" height="1" alt=""></td><td width="87%" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="166" height="1" alt=""></td><td width="5" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002">' .
                                     '<img src="images/pixel_trans.gif" width="5" height="1" alt=""></td><td width="1" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="1" height="1" alt=""></td><td width="90" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif"  height="1" alt=""></td><td width="1" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002">' .
                                     '<img src="images/pixel_trans.gif" width="1" height="1" alt=""></td><td width="90" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif"  height="1" alt=""></td><td width="1" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="1" height="1" alt=""></td><td width="90" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002" >' . 
                                     '<img src="images/pixel_trans.gif"  height="1" alt=""></td><td width="1" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="1" height="1" alt=""></td></tr><tr style="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><td bgcolor="#CFCFCF" width="1" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002">');

define('CONTENT_TEXT3','<img src="images/pixel_trans.gif" width="1" height="1" alt=""></td><td colspan="9" bgcolor="#CFCFCF" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="1" height="1" alt=""></td><td bgcolor="#CFCFCF" width="1" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="1" height="1" alt=""></td>' .
                                     '</tr><tr><td bgcolor="#CFCFCF" height="40" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="1" height="1" alt=""></td><font face="arial, helvetica, sans-serif"><td height="40" bgcolor="#E7EFFF" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="5" height="1" alt=""></td></FONT>' .
                                     '<td class="body" height="40" bgcolor="#E7EFFF" colspan="8"><p style="margin-top: 4px; margin-bottom: 4px"><font face="Arial" color="#003399" style="font-size: 16pt">Basic</font></p><p style="margin-top: 4px; margin-bottom: 4px"><span style="font-weight: 700"> <font face="Arial" size="3" color="#666666">$79.95/mo</font></span></td><font face="arial, helvetica, sans-serif">' .
                                     '<td bgcolor="#CFCFCF" height="40" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="1" height="1" alt=""></td></FONT></tr><tr><td bgcolor="#CFCFCF" width="1" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="1" height="1" alt=""></td>  <td colspan="9" bgcolor="#CFCFCF" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002">' .
                                     '<img src="images/pixel_trans.gif" width="1" height="1" alt=""></td><td bgcolor="#CFCFCF" width="1" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="1" height="1" alt=""></td></tr><tr><td bgcolor="#CFCFCF" height="25" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="1" height="1" alt=""></td>' .
                                     '<td height="25" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="7" height="1" alt=""></td><td class="body" height="25" colspan="8"><br><font color="#666666">No setup fee,<br>$1 to $1.50 handling fee</font><font color="#003399"><br>&nbsp;</font><table cellpadding="0" cellspacing="0" border="0" id="table746">' .
                                     '<tr><td class="faqLinks"><table border="0" width="100%" cellspacing="0" cellpadding="0" id="table747"><tr><td valign="top" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><table border="0" width="100%" cellspacing="0" cellpadding="0" id="table748"><tr><td height="18" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><FONT face="arial, helvetica, sans-serif" style="font-size: 9pt">');

define('CONTENT_TEXT4','<img src="http://www.shipwire.com/exec/images/blackbullet.gif" width="4" height="4" hspace="8" align="middle"></FONT></td></tr></table></td><td width="100%" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><FONT face="arial, helvetica, sans-serif" size="2"><span style="font-size:9pt;font-family:Arial; color:#000002"><span class="lb08"><font face="Arial" color="#666666">Easy setup with your store</font></span></span></font></td>' .
                                     '</tr></table></td></tr><tr><td class="faqLinks"><table border="0" width="100%" cellspacing="0" cellpadding="0" id="table749"><tr><td valign="top" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><table border="0" width="100%" cellspacing="0" cellpadding="0" id="table750"><tr><td height="18" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002">' .
                                     '  <FONT face="arial, helvetica, sans-serif" style="font-size: 9pt"><img src="http://www.shipwire.com/exec/images/blackbullet.gif" width="4" height="4" hspace="8" align="middle"></FONT></td></tr></table></td><td width="100%" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><FONT face="arial, helvetica, sans-serif" size="2"><span style="font-size:9pt;font-family:Arial; color:#000002">' .
                                     '<span class="lb08"><font face="Arial" color="#666666">Online inventory manager</font></span></span></font></td></tr></table></td></tr><tr><td class="faqLinks"><table border="0" width="100%" cellspacing="0" cellpadding="0" id="table751"><tr><td valign="top" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><table border="0" width="100%" cellspacing="0" cellpadding="0" id="table752">' .
                                     '<tr><td height="18" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><FONT face="arial, helvetica, sans-serif" style="font-size: 9pt"><img src="http://www.shipwire.com/exec/images/blackbullet.gif" width="4" height="4" hspace="8" align="middle"></FONT></td></tr></table></td><td width="100%" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002">' .
                                     '<FONT face="arial, helvetica, sans-serif" size="2"><span style="font-size:9pt;font-family:Arial; color:#000002"><span class="lb08"><font face="Arial" color="#666666">Sell up to 50 items</font></span></span></font></td></tr></table></td></tr><tr><td class="faqLinks"><table border="0" width="100%" cellspacing="0" cellpadding="0" id="table753"><tr><td valign="top" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002">' .
                                     '<table border="0" width="100%" cellspacing="0" cellpadding="0" id="table754"><tr><td height="18" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><FONT face="arial, helvetica, sans-serif" style="font-size: 9pt"><img src="http://www.shipwire.com/exec/images/blackbullet.gif" width="4" height="4" hspace="8" align="middle"></FONT></td></tr></table></td>');

define('CONTENT_TEXT5','<td width="100%" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><FONT face="arial, helvetica, sans-serif" size="2"><span style="font-size:9pt;font-family:Arial; color:#000002"><span class="lb08"><font face="Arial" color="#666666">Unlimited email support</font></span></span></font></td></tr></table></td></tr></table><p ALIGN="center"><span style="font-family: Verdana; font-size: 10px; color:#000002">' .
                                     '<font face="Arial" size="2" color="#000000"><a TARGET="_blank" HREF="http://www.shipwire.com/exec/creloaded.php?ref=6133361"><input type="button" value="Free Sign Up" onclick="\'document.location.href=create_account.php\'" style="font-family:Arial; font-size:13px; "></a>&nbsp;&nbsp;&nbsp; </font></span><br><br>&nbsp;&nbsp;</p></td><td bgcolor="#CFCFCF" height="25" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002">' .
                                     '<img src="images/pixel_trans.gif" width="1" height="1" alt=""></td></tr><tr><td bgcolor="#CFCFCF" width="1" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"><img src="images/pixel_trans.gif" width="1" height="1" alt=""></td><font face="arial, helvetica, sans-serif"><td colspan="9" bgcolor="#CFCFCF" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002">' .
                                     '<img src="images/pixel_trans.gif" width="1" height="1" alt=""></td><font face="arial, helvetica, sans-serif" size="2"><td bgcolor="#CFCFCF" width="1" STYLE="font-family: Verdana, Arial, Helvetica; font-size; color: #000002"></FONT></FONT></tr></table></span></span></font></td></tr></table></font></td></tr></table></div>');

?>