template: mailhive/common/templates/email_html_zencart.tpl.
<br>
Zencart merges the output generated by MailBeez into the zencart default template located in <br>
email/email_template_default.html<br>
<br>
Upgrade to the <b><a href="http://www.mailbeez.com/documentation/configbeez/config_tmplmngr/?a={$smarty.const.MH_ID}"
                     target="_blank">MailBeez Template
    Manager</a></b> to edit all your MailBeez Templates in your MailBeez Admin
<br><br>
<br>

{$body}

<br clear="all">
<hr>
Please send me <a href="{$block_url}">no more emails like this</a>.
We sent you this email since we have registered your email-address: {$email_address|default:'me@mail.com'} in our customer database.
Please do not reply to this email. If you would like to contact us, please use our Customer Service.
<br>
<br>
<!-- please keep this link - and/or donate on www.mailbeez.com/thank-you -->
<img src="{$catalog_server}mailhive/common/images/been_tiny.gif" border="0" hspace="0" vspace="0" width="33" height="28"
     align="absmiddle"> powered by <a href="http://www.MailBeez.com"
                                      target="_blank">MailBeez.com</a>  with Smarty {$smarty.version}
<hr>