#
# Data for table: address_book
#
INSERT INTO `address_book` VALUES (1, 1, 'm', 'Loaded Commerce, LLC', '', 'Sal', 'Iozzia', '1211 CR 436', '', '33538', 'Panasoffkee', '', 223, 18, '800.609.2141', '', 'sal@loadedcommerce.com');


#
# Data for table: address_format
#
INSERT INTO address_format VALUES( 1, '$firstname $lastname$cr$streets$cr$city, $postcode$cr$statecomma$country', '$city / $country');
INSERT INTO address_format VALUES( 2, '$firstname $lastname$cr$streets$cr$city, $state    $postcode$cr$country', '$city, $state / $country');
INSERT INTO address_format VALUES( 3, '$firstname $lastname$cr$streets$cr$city$cr$postcode - $statecomma$country', '$state / $country');
INSERT INTO address_format VALUES( 4, '$firstname $lastname$cr$streets$cr$city ($postcode)$cr$country', '$postcode / $country');
INSERT INTO address_format VALUES( 5, '$firstname $lastname$cr$streets$cr$postcode $city$cr$country', '$city / $country');
INSERT INTO address_format VALUES( 6, '$firstname $lastname$cr$streets$cr$city$cr$postcode$cr$country', '$city / $country');
INSERT INTO address_format VALUES( 7, '$firstname $lastname$cr$streets$cr$city$cr$state$cr$country', '$city / $country');
INSERT INTO address_format VALUES( 8, '$firstname $lastname$cr$streets$cr$city $postcode$cr$country', '$city / $country');
INSERT INTO address_format VALUES( 9, '$firstname $lastname$cr$streets$cr$postcode $city $state$cr$country', '$city / $country');
INSERT INTO address_format VALUES( 10, '$firstname $lastname$cr$streets$cr$city$cr$postcode $country', '$city / $country');
INSERT INTO address_format VALUES( 11, '$firstname $lastname$cr$streets$cr$city$cr$state$cr$postcode$cr$country', '$city / $country');
INSERT INTO address_format VALUES( 12, '$firstname $lastname$cr$streets$cr$city$cr$country $postcode', '$city / $country');


#
# Data for table: admin_files
#
INSERT INTO admin_files VALUES( 1, 'administrator.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 2, 'configuration.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 3, 'catalog.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 4, 'modules.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 5, 'customers.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 6, 'taxes.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 7, 'localization.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 8, 'reports.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 9, 'tools.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 10, 'design_controls.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 11, 'gv_admin.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 12, 'links.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 13, 'event_drop_dns.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 14, 'faq.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 15, 'data.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 16, 'articles.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 19, 'marketing.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 20, 'information.php',  1,  0, '1');
INSERT INTO admin_files VALUES( 100, 'admin_members.php',  0,  1, '1');
INSERT INTO admin_files VALUES( 101, 'admin_files.php',  0,  1, '1');
INSERT INTO admin_files VALUES( 102, 'admin_account.php',  0,  1, '1');
INSERT INTO admin_files VALUES( 103, 'validate_new.php',  0,  1, '1');
INSERT INTO admin_files VALUES( 104, 'ssl_check.php',  0,  1, '1');
INSERT INTO admin_files VALUES( 105, 'feature_not_present.php',  0,  1, '1');
INSERT INTO admin_files VALUES( 106, 'rsslink.php',  0,  1, '1');
INSERT INTO admin_files VALUES( 200, 'configuration.php',  0,  2, '1');
INSERT INTO admin_files VALUES( 201, 'shipwire.php',  0,  2, '1');
INSERT INTO admin_files VALUES( 300, 'categories.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 301, 'products_attributes.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 302, 'manufacturers.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 304, 'reviews.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 305, 'shopbyprice.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 306, 'products_expected.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 307, 'xsell_products.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 308, 'define_mainpage.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 309, 'salemaker.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 310, 'listcategories.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 311, 'quick_attributes_popup.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 312, 'quick_products_popup.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 313, 'featured.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 314, 'salemaker_info.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 315, 'epconfigure.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 316, 'products_multi.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 317, 'feature_not_present.php',  0,  3, '1');
INSERT INTO admin_files VALUES( 400, 'modules.php',  0,  4, '1');
INSERT INTO admin_files VALUES( 500, 'customers.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 501, 'orders.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 502, 'paypal.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 503, 'edit_orders.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 504, 'create_account_success.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 505, 'create_account_process.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 506, 'create_order.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 507, 'create_account.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 508, 'create_order_process.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 509, 'account_details.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 510, 'ipn_test_panel.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 511, 'results.inc.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 512, 'members.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 513, 'create_order_admin.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 514, 'create_order_payment.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 515, 'create_order_shipping.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 516, 'abandoned_orders.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 517, 'cre_marketplace.php',  0,  5, '1');
INSERT INTO admin_files VALUES( 600, 'countries.php',  0,  6, '1');
INSERT INTO admin_files VALUES( 601, 'zones.php',  0,  6, '1');
INSERT INTO admin_files VALUES( 602, 'geo_zones.php',  0,  6, '1');
INSERT INTO admin_files VALUES( 603, 'tax_classes.php',  0,  6, '1');
INSERT INTO admin_files VALUES( 604, 'tax_rates.php',  0,  6, '1');
INSERT INTO admin_files VALUES( 700, 'currencies.php',  0,  7, '1');
INSERT INTO admin_files VALUES( 701, 'languages.php',  0,  7, '1');
INSERT INTO admin_files VALUES( 702, 'orders_status.php',  0,  7, '1');
INSERT INTO admin_files VALUES( 800, 'stats_products_viewed.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 801, 'stats_products_purchased.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 802, 'stats_customers.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 803, 'stats_monthly_sales.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 804, 'orderlist.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 805, 'stats_sales_report2.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 806, 'stats_customers_orders.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 807, 'stats_daily_products_sales_report.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 808, 'stats_wishlist.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 809, 'stats_articles_viewed.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 810, 'stats_products_notifications.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 811, 'stats_not_valid_users.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 812, 'stats_low_stock.php',  0,  8, '1');
INSERT INTO admin_files VALUES( 900, 'backup.php',  0,  9, '1');
INSERT INTO admin_files VALUES( 901, 'cache.php',  0,  9, '1');
INSERT INTO admin_files VALUES( 902, 'define_language.php',  0,  9, '1');
INSERT INTO admin_files VALUES( 903, 'mail.php',  0,  9, '1');
INSERT INTO admin_files VALUES( 905, 'server_info.php',  0,  9, '1');
INSERT INTO admin_files VALUES( 906, 'whos_online.php',  0,  9, '1');
INSERT INTO admin_files VALUES( 907, 'backup_mysql.php',  0,  9, '1');
INSERT INTO admin_files VALUES( 909, 'edit_textdata.php',  0,  9, '1');
INSERT INTO admin_files VALUES( 910, 'edit_textdata_help.php',  0,  9, '1');
INSERT INTO admin_files VALUES( 911, 'email_subjects.php',  0,  9, '1');
INSERT INTO admin_files VALUES( 912, 'check_lang.php',  0,  9, '1');
INSERT INTO admin_files VALUES( 1000, 'infobox_configuration.php',  0,  10, '1');
INSERT INTO admin_files VALUES( 1001, 'template_configuration.php',  0,  10, '1');
INSERT INTO admin_files VALUES( 1002, 'header_tags_fill_tags.php',  0,  10, '1');
INSERT INTO admin_files VALUES( 1003, 'header_tags_english.php',  0,  10, '1');
INSERT INTO admin_files VALUES( 1004, 'header_tags_controller.php',  0,  10, '1');
INSERT INTO admin_files VALUES( 1005, 'template_admin.php',  0,  10, '1');
INSERT INTO admin_files VALUES( 1006, 'header_tags_popup_help.php',  0,  10, '1');
INSERT INTO admin_files VALUES( 1007, 'branding_manager.php',  0,  10, '1');
INSERT INTO admin_files VALUES( 1100, 'coupon_admin.php',  0,  11, '1');
INSERT INTO admin_files VALUES( 1101, 'gv_queue.php',  0,  11, '1');
INSERT INTO admin_files VALUES( 1102, 'gv_mail.php',  0,  11, '1');
INSERT INTO admin_files VALUES( 1103, 'gv_sent.php',  0,  11, '1');
INSERT INTO admin_files VALUES( 1104, 'coupon_restrict.php',  0,  11, '1');
INSERT INTO admin_files VALUES( 1105, 'validcategories.php',  0,  11, '1');
INSERT INTO admin_files VALUES( 1106, 'validproducts.php',  0,  11, '1');
INSERT INTO admin_files VALUES( 1107, 'listproducts.php',  0,  11, '1');
INSERT INTO admin_files VALUES( 1108, 'gv_report.php',  0,  11, '1');
INSERT INTO admin_files VALUES( 1109, 'treeview.php',  0,  11, '1');
INSERT INTO admin_files VALUES( 1200, 'links.php',  0,  12, '1');
INSERT INTO admin_files VALUES( 1201, 'link_categories.php',  0,  12, '1');
INSERT INTO admin_files VALUES( 1202, 'links_contact.php',  0,  12, '1');
INSERT INTO admin_files VALUES( 1300, 'event_drop_dns.php',  0,  13, '1');
INSERT INTO admin_files VALUES( 1400, 'faq_manager.php',  0,  14, '1');
INSERT INTO admin_files VALUES( 1401, 'faq_list.php',  0,  14, '1');
INSERT INTO admin_files VALUES( 1402, 'faq_form.php',  0,  14, '1');
INSERT INTO admin_files VALUES( 1403, 'faq_view.php',  0,  14, '1');
INSERT INTO admin_files VALUES( 1404, 'faq_view_all.php',  0,  14, '1');
INSERT INTO admin_files VALUES( 1405, 'faq_categories.php',  0,  14, '1');
INSERT INTO admin_files VALUES( 1500, 'data.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1501, 'data_admin.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1502, 'data_help.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1503, 'easypopulate_basic_export.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1504, 'easypopulate_basic_import.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1505, 'easypopulate_export.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1506, 'easypopulate_import.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1507, 'popup_data_help.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1508, 'popup_ep_help.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1509, 'google.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1510, 'google_admin.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1511, 'google_configure.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1512, 'google_pre.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1513, 'google_pre1.php',  0,  15, '1');
INSERT INTO admin_files VALUES( 1600, 'authors.php',  0,  16, '1');
INSERT INTO admin_files VALUES( 1601, 'articles_xsell.php',  0,  16, '1');
INSERT INTO admin_files VALUES( 1602, 'articles_config.php',  0,  16, '1');
INSERT INTO admin_files VALUES( 1603, 'articles.php',  0,  16, '1');
INSERT INTO admin_files VALUES( 1604, 'article_reviews.php',  0,  16, '1');
INSERT INTO admin_files VALUES( 1900, 'banner_statistics.php',  0,  19, '1');
INSERT INTO admin_files VALUES( 1901, 'banner_manager.php',  0,  19, '1');
INSERT INTO admin_files VALUES( 1902, 'specials.php',  0,  19, '1');
INSERT INTO admin_files VALUES( 1903, 'newsletters.php',  0,  19, '1');
INSERT INTO admin_files VALUES( 2000, 'pages.php',  0,  20, '1');
INSERT INTO admin_files VALUES( 2001, 'pages_categories.php',  0,  20, '1');


#
# Data for table: admin_groups
#
INSERT INTO admin_groups VALUES( 1, 'Top Administrator');


#
# Data for table: branding_description
#
INSERT INTO branding_description VALUES('LoadedCommerceSiteLogo.png', 'loaded-favicon-64.gif', '', '216.220.8766', '216.220.8768', 'http://www.loadedcommerce.com/', 'Loaded Commerce Professional B2B', 'sales@loadedcommerce.com', '800.609.2141', 'Loaded Commerce, LLC\n1211 CR 436\nLake Panasoffkee, FL 33538\nPhone: 216.220.8766\nToll-Free: 800.609.2141\nFax: 216.220.8768', 'https://www.facebook.com/loadedcommerce', 'https://twitter.com/loadedcommerce', '', '', '', '', '', '',1);


#
# Data for table: countries
#
INSERT INTO countries VALUES( 1, 'Afghanistan', 'AF', 'AFG',  1);
INSERT INTO countries VALUES( 2, 'Albania', 'AL', 'ALB',  1);
INSERT INTO countries VALUES( 3, 'Algeria', 'DZ', 'DZA',  1);
INSERT INTO countries VALUES( 4, 'American Samoa', 'AS', 'ASM',  1);
INSERT INTO countries VALUES( 5, 'Andorra', 'AD', 'AND',  1);
INSERT INTO countries VALUES( 6, 'Angola', 'AO', 'AGO',  1);
INSERT INTO countries VALUES( 7, 'Anguilla', 'AI', 'AIA',  1);
INSERT INTO countries VALUES( 8, 'Antarctica', 'AQ', 'ATA',  1);
INSERT INTO countries VALUES( 9, 'Antigua and Barbuda', 'AG', 'ATG',  1);
INSERT INTO countries VALUES( 10, 'Argentina', 'AR', 'ARG',  1);
INSERT INTO countries VALUES( 11, 'Armenia', 'AM', 'ARM',  1);
INSERT INTO countries VALUES( 12, 'Aruba', 'AW', 'ABW',  1);
INSERT INTO countries VALUES( 13, 'Australia', 'AU', 'AUS',  2);
INSERT INTO countries VALUES( 14, 'Austria', 'AT', 'AUT',  5);
INSERT INTO countries VALUES( 15, 'Azerbaijan', 'AZ', 'AZE',  1);
INSERT INTO countries VALUES( 16, 'Bahamas', 'BS', 'BHS',  1);
INSERT INTO countries VALUES( 17, 'Bahrain', 'BH', 'BHR',  1);
INSERT INTO countries VALUES( 18, 'Bangladesh', 'BD', 'BGD',  1);
INSERT INTO countries VALUES( 19, 'Barbados', 'BB', 'BRB',  1);
INSERT INTO countries VALUES( 20, 'Belarus', 'BY', 'BLR',  1);
INSERT INTO countries VALUES( 21, 'Belgium', 'BE', 'BEL',  5);
INSERT INTO countries VALUES( 22, 'Belize', 'BZ', 'BLZ',  1);
INSERT INTO countries VALUES( 23, 'Benin', 'BJ', 'BEN',  1);
INSERT INTO countries VALUES( 24, 'Bermuda', 'BM', 'BMU',  1);
INSERT INTO countries VALUES( 25, 'Bhutan', 'BT', 'BTN',  1);
INSERT INTO countries VALUES( 26, 'Bolivia', 'BO', 'BOL',  1);
INSERT INTO countries VALUES( 27, 'Bosnia and Herzegowina', 'BA', 'BIH',  1);
INSERT INTO countries VALUES( 28, 'Botswana', 'BW', 'BWA',  1);
INSERT INTO countries VALUES( 29, 'Bouvet Island', 'BV', 'BVT',  1);
INSERT INTO countries VALUES( 30, 'Brazil', 'BR', 'BRA',  6);
INSERT INTO countries VALUES( 31, 'British Indian Ocean Territory', 'IO', 'IOT',  1);
INSERT INTO countries VALUES( 32, 'Brunei Darussalam', 'BN', 'BRN',  1);
INSERT INTO countries VALUES( 33, 'Bulgaria', 'BG', 'BGR',  1);
INSERT INTO countries VALUES( 34, 'Burkina Faso', 'BF', 'BFA',  1);
INSERT INTO countries VALUES( 35, 'Burundi', 'BI', 'BDI',  1);
INSERT INTO countries VALUES( 36, 'Cambodia', 'KH', 'KHM',  1);
INSERT INTO countries VALUES( 37, 'Cameroon', 'CM', 'CMR',  1);
INSERT INTO countries VALUES( 38, 'Canada', 'CA', 'CAN',  2);
INSERT INTO countries VALUES( 39, 'Cape Verde', 'CV', 'CPV',  1);
INSERT INTO countries VALUES( 40, 'Cayman Islands', 'KY', 'CYM',  1);
INSERT INTO countries VALUES( 41, 'Central African Republic', 'CF', 'CAF',  1);
INSERT INTO countries VALUES( 42, 'Chad', 'TD', 'TCD',  1);
INSERT INTO countries VALUES( 43, 'Chile', 'CL', 'CHL',  1);
INSERT INTO countries VALUES( 44, 'China', 'CN', 'CHN',  5);
INSERT INTO countries VALUES( 45, 'Christmas Island', 'CX', 'CXR',  1);
INSERT INTO countries VALUES( 46, 'Cocos (Keeling) Islands', 'CC', 'CCK',  1);
INSERT INTO countries VALUES( 47, 'Colombia', 'CO', 'COL',  1);
INSERT INTO countries VALUES( 48, 'Comoros', 'KM', 'COM',  1);
INSERT INTO countries VALUES( 49, 'Congo', 'CG', 'COG',  1);
INSERT INTO countries VALUES( 50, 'Cook Islands', 'CK', 'COK',  1);
INSERT INTO countries VALUES( 51, 'Costa Rica', 'CR', 'CRI',  1);
INSERT INTO countries VALUES( 52, 'Cote D\'Ivoire', 'CI', 'CIV',  1);
INSERT INTO countries VALUES( 53, 'Croatia', 'HR', 'HRV',  1);
INSERT INTO countries VALUES( 54, 'Cuba', 'CU', 'CUB',  1);
INSERT INTO countries VALUES( 55, 'Cyprus', 'CY', 'CYP',  1);
INSERT INTO countries VALUES( 56, 'Czech Republic', 'CZ', 'CZE',  1);
INSERT INTO countries VALUES( 57, 'Denmark', 'DK', 'DNK',  5);
INSERT INTO countries VALUES( 58, 'Djibouti', 'DJ', 'DJI',  1);
INSERT INTO countries VALUES( 59, 'Dominica', 'DM', 'DMA',  1);
INSERT INTO countries VALUES( 60, 'Dominican Republic', 'DO', 'DOM',  1);
INSERT INTO countries VALUES( 61, 'East Timor', 'TP', 'TMP',  1);
INSERT INTO countries VALUES( 62, 'Ecuador', 'EC', 'ECU',  1);
INSERT INTO countries VALUES( 63, 'Egypt', 'EG', 'EGY',  1);
INSERT INTO countries VALUES( 64, 'El Salvador', 'SV', 'SLV',  1);
INSERT INTO countries VALUES( 65, 'Equatorial Guinea', 'GQ', 'GNQ',  1);
INSERT INTO countries VALUES( 66, 'Eritrea', 'ER', 'ERI',  1);
INSERT INTO countries VALUES( 67, 'Estonia', 'EE', 'EST',  1);
INSERT INTO countries VALUES( 68, 'Ethiopia', 'ET', 'ETH',  1);
INSERT INTO countries VALUES( 69, 'Falkland Islands (Malvinas)', 'FK', 'FLK',  1);
INSERT INTO countries VALUES( 70, 'Faroe Islands', 'FO', 'FRO',  1);
INSERT INTO countries VALUES( 71, 'Fiji', 'FJ', 'FJI',  1);
INSERT INTO countries VALUES( 72, 'Finland', 'FI', 'FIN',  5);
INSERT INTO countries VALUES( 73, 'France', 'FR', 'FRA',  5);
INSERT INTO countries VALUES( 74, 'France, Metropolitan', 'FX', 'FXX',  1);
INSERT INTO countries VALUES( 75, 'French Guiana', 'GF', 'GUF',  1);
INSERT INTO countries VALUES( 76, 'French Polynesia', 'PF', 'PYF',  1);
INSERT INTO countries VALUES( 77, 'French Southern Territories', 'TF', 'ATF',  1);
INSERT INTO countries VALUES( 78, 'Gabon', 'GA', 'GAB',  1);
INSERT INTO countries VALUES( 79, 'Gambia', 'GM', 'GMB',  1);
INSERT INTO countries VALUES( 80, 'Georgia', 'GE', 'GEO',  1);
INSERT INTO countries VALUES( 81, 'Germany', 'DE', 'DEU',  5);
INSERT INTO countries VALUES( 82, 'Ghana', 'GH', 'GHA',  1);
INSERT INTO countries VALUES( 83, 'Gibraltar', 'GI', 'GIB',  1);
INSERT INTO countries VALUES( 84, 'Greece', 'GR', 'GRC',  1);
INSERT INTO countries VALUES( 85, 'Greenland', 'GL', 'GRL',  5);
INSERT INTO countries VALUES( 86, 'Grenada', 'GD', 'GRD',  1);
INSERT INTO countries VALUES( 87, 'Guadeloupe', 'GP', 'GLP',  1);
INSERT INTO countries VALUES( 88, 'Guam', 'GU', 'GUM',  1);
INSERT INTO countries VALUES( 89, 'Guatemala', 'GT', 'GTM',  1);
INSERT INTO countries VALUES( 90, 'Guinea', 'GN', 'GIN',  1);
INSERT INTO countries VALUES( 91, 'Guinea-bissau', 'GW', 'GNB',  1);
INSERT INTO countries VALUES( 92, 'Guyana', 'GY', 'GUY',  1);
INSERT INTO countries VALUES( 93, 'Haiti', 'HT', 'HTI',  1);
INSERT INTO countries VALUES( 94, 'Heard and Mc Donald Islands', 'HM', 'HMD',  1);
INSERT INTO countries VALUES( 95, 'Honduras', 'HN', 'HND',  1);
INSERT INTO countries VALUES( 96, 'Hong Kong', 'HK', 'HKG',  7);
INSERT INTO countries VALUES( 97, 'Hungary', 'HU', 'HUN',  1);
INSERT INTO countries VALUES( 98, 'Iceland', 'IS', 'ISL',  5);
INSERT INTO countries VALUES( 99, 'India', 'IN', 'IND',  8);
INSERT INTO countries VALUES( 100, 'Indonesia', 'ID', 'IDN',  8);
INSERT INTO countries VALUES( 101, 'Iran (Islamic Republic of)', 'IR', 'IRN',  1);
INSERT INTO countries VALUES( 102, 'Iraq', 'IQ', 'IRQ',  1);
INSERT INTO countries VALUES( 103, 'Ireland', 'IE', 'IRL',  8);
INSERT INTO countries VALUES( 104, 'Israel', 'IL', 'ISR',  5);
INSERT INTO countries VALUES( 105, 'Italy', 'IT', 'ITA',  9);
INSERT INTO countries VALUES( 106, 'Jamaica', 'JM', 'JAM',  1);
INSERT INTO countries VALUES( 107, 'Japan', 'JP', 'JPN',  2);
INSERT INTO countries VALUES( 108, 'Jordan', 'JO', 'JOR',  1);
INSERT INTO countries VALUES( 109, 'Kazakhstan', 'KZ', 'KAZ',  1);
INSERT INTO countries VALUES( 110, 'Kenya', 'KE', 'KEN',  1);
INSERT INTO countries VALUES( 111, 'Kiribati', 'KI', 'KIR',  1);
INSERT INTO countries VALUES( 112, 'Korea, Democratic People\'s Republic of', 'KP', 'PRK',  8);
INSERT INTO countries VALUES( 113, 'Korea, Republic of', 'KR', 'KOR',  8);
INSERT INTO countries VALUES( 114, 'Kuwait', 'KW', 'KWT',  1);
INSERT INTO countries VALUES( 115, 'Kyrgyzstan', 'KG', 'KGZ',  1);
INSERT INTO countries VALUES( 116, 'Lao People\'s Democratic Republic', 'LA', 'LAO',  1);
INSERT INTO countries VALUES( 117, 'Latvia', 'LV', 'LVA',  1);
INSERT INTO countries VALUES( 118, 'Lebanon', 'LB', 'LBN',  1);
INSERT INTO countries VALUES( 119, 'Lesotho', 'LS', 'LSO',  1);
INSERT INTO countries VALUES( 120, 'Liberia', 'LR', 'LBR',  1);
INSERT INTO countries VALUES( 121, 'Libyan Arab Jamahiriya', 'LY', 'LBY',  1);
INSERT INTO countries VALUES( 122, 'Liechtenstein', 'LI', 'LIE',  1);
INSERT INTO countries VALUES( 123, 'Lithuania', 'LT', 'LTU',  1);
INSERT INTO countries VALUES( 124, 'Luxembourg', 'LU', 'LUX',  5);
INSERT INTO countries VALUES( 125, 'Macau', 'MO', 'MAC',  1);
INSERT INTO countries VALUES( 126, 'Macedonia, The Former Yugoslav Republic of', 'MK', 'MKD',  1);
INSERT INTO countries VALUES( 127, 'Madagascar', 'MG', 'MDG',  1);
INSERT INTO countries VALUES( 128, 'Malawi', 'MW', 'MWI',  1);
INSERT INTO countries VALUES( 129, 'Malaysia', 'MY', 'MYS',  1);
INSERT INTO countries VALUES( 130, 'Maldives', 'MV', 'MDV',  1);
INSERT INTO countries VALUES( 131, 'Mali', 'ML', 'MLI',  1);
INSERT INTO countries VALUES( 132, 'Malta', 'MT', 'MLT',  1);
INSERT INTO countries VALUES( 133, 'Marshall Islands', 'MH', 'MHL',  1);
INSERT INTO countries VALUES( 134, 'Martinique', 'MQ', 'MTQ',  1);
INSERT INTO countries VALUES( 135, 'Mauritania', 'MR', 'MRT',  1);
INSERT INTO countries VALUES( 136, 'Mauritius', 'MU', 'MUS',  1);
INSERT INTO countries VALUES( 137, 'Mayotte', 'YT', 'MYT',  1);
INSERT INTO countries VALUES( 138, 'Mexico', 'MX', 'MEX',  9);
INSERT INTO countries VALUES( 139, 'Micronesia, Federated States of', 'FM', 'FSM',  1);
INSERT INTO countries VALUES( 140, 'Moldova, Republic of', 'MD', 'MDA',  1);
INSERT INTO countries VALUES( 141, 'Monaco', 'MC', 'MCO',  1);
INSERT INTO countries VALUES( 142, 'Mongolia', 'MN', 'MNG',  1);
INSERT INTO countries VALUES( 143, 'Montserrat', 'MS', 'MSR',  1);
INSERT INTO countries VALUES( 144, 'Morocco', 'MA', 'MAR',  1);
INSERT INTO countries VALUES( 145, 'Mozambique', 'MZ', 'MOZ',  1);
INSERT INTO countries VALUES( 146, 'Myanmar', 'MM', 'MMR',  1);
INSERT INTO countries VALUES( 147, 'Namibia', 'NA', 'NAM',  1);
INSERT INTO countries VALUES( 148, 'Nauru', 'NR', 'NRU',  1);
INSERT INTO countries VALUES( 149, 'Nepal', 'NP', 'NPL',  1);
INSERT INTO countries VALUES( 150, 'Netherlands', 'NL', 'NLD',  5);
INSERT INTO countries VALUES( 151, 'Netherlands Antilles', 'AN', 'ANT',  1);
INSERT INTO countries VALUES( 152, 'New Caledonia', 'NC', 'NCL',  1);
INSERT INTO countries VALUES( 153, 'New Zealand', 'NZ', 'NZL',  8);
INSERT INTO countries VALUES( 154, 'Nicaragua', 'NI', 'NIC',  1);
INSERT INTO countries VALUES( 155, 'Niger', 'NE', 'NER',  1);
INSERT INTO countries VALUES( 156, 'Nigeria', 'NG', 'NGA',  1);
INSERT INTO countries VALUES( 157, 'Niue', 'NU', 'NIU',  1);
INSERT INTO countries VALUES( 158, 'Norfolk Island', 'NF', 'NFK',  1);
INSERT INTO countries VALUES( 159, 'Northern Mariana Islands', 'MP', 'MNP',  1);
INSERT INTO countries VALUES( 160, 'Norway', 'NO', 'NOR',  5);
INSERT INTO countries VALUES( 161, 'Oman', 'OM', 'OMN',  1);
INSERT INTO countries VALUES( 162, 'Pakistan', 'PK', 'PAK',  1);
INSERT INTO countries VALUES( 163, 'Palau', 'PW', 'PLW',  1);
INSERT INTO countries VALUES( 164, 'Panama', 'PA', 'PAN',  1);
INSERT INTO countries VALUES( 165, 'Papua New Guinea', 'PG', 'PNG',  1);
INSERT INTO countries VALUES( 166, 'Paraguay', 'PY', 'PRY',  1);
INSERT INTO countries VALUES( 167, 'Peru', 'PE', 'PER',  1);
INSERT INTO countries VALUES( 168, 'Philippines', 'PH', 'PHL',  1);
INSERT INTO countries VALUES( 169, 'Pitcairn', 'PN', 'PCN',  1);
INSERT INTO countries VALUES( 170, 'Poland', 'PL', 'POL',  5);
INSERT INTO countries VALUES( 171, 'Portugal', 'PT', 'PRT',  5);
INSERT INTO countries VALUES( 172, 'Puerto Rico', 'PR', 'PRI',  1);
INSERT INTO countries VALUES( 173, 'Qatar', 'QA', 'QAT',  1);
INSERT INTO countries VALUES( 174, 'Reunion', 'RE', 'REU',  1);
INSERT INTO countries VALUES( 175, 'Romania', 'RO', 'ROM',  1);
INSERT INTO countries VALUES( 176, 'Russian Federation', 'RU', 'RUS',  5);
INSERT INTO countries VALUES( 177, 'Rwanda', 'RW', 'RWA',  1);
INSERT INTO countries VALUES( 178, 'Saint Kitts and Nevis', 'KN', 'KNA',  1);
INSERT INTO countries VALUES( 179, 'Saint Lucia', 'LC', 'LCA',  1);
INSERT INTO countries VALUES( 180, 'Saint Vincent and the Grenadines', 'VC', 'VCT',  1);
INSERT INTO countries VALUES( 181, 'Samoa', 'WS', 'WSM',  1);
INSERT INTO countries VALUES( 182, 'San Marino', 'SM', 'SMR',  1);
INSERT INTO countries VALUES( 183, 'Sao Tome and Principe', 'ST', 'STP',  1);
INSERT INTO countries VALUES( 184, 'Saudi Arabia', 'SA', 'SAU',  1);
INSERT INTO countries VALUES( 185, 'Senegal', 'SN', 'SEN',  1);
INSERT INTO countries VALUES( 186, 'Seychelles', 'SC', 'SYC',  1);
INSERT INTO countries VALUES( 187, 'Sierra Leone', 'SL', 'SLE',  1);
INSERT INTO countries VALUES( 188, 'Singapore', 'SG', 'SGP',  12);
INSERT INTO countries VALUES( 189, 'Slovakia (Slovak Republic)', 'SK', 'SVK',  1);
INSERT INTO countries VALUES( 190, 'Slovenia', 'SI', 'SVN',  1);
INSERT INTO countries VALUES( 191, 'Solomon Islands', 'SB', 'SLB',  1);
INSERT INTO countries VALUES( 192, 'Somalia', 'SO', 'SOM',  1);
INSERT INTO countries VALUES( 193, 'South Africa', 'ZA', 'ZAF',  10);
INSERT INTO countries VALUES( 194, 'South Georgia and the South Sandwich Islands', 'GS', 'SGS',  1);
INSERT INTO countries VALUES( 195, 'Spain', 'ES', 'ESP',  3);
INSERT INTO countries VALUES( 196, 'Sri Lanka', 'LK', 'LKA',  1);
INSERT INTO countries VALUES( 197, 'St. Helena', 'SH', 'SHN',  1);
INSERT INTO countries VALUES( 198, 'St. Pierre and Miquelon', 'PM', 'SPM',  1);
INSERT INTO countries VALUES( 199, 'Sudan', 'SD', 'SDN',  1);
INSERT INTO countries VALUES( 200, 'Suriname', 'SR', 'SUR',  1);
INSERT INTO countries VALUES( 201, 'Svalbard and Jan Mayen Islands', 'SJ', 'SJM',  1);
INSERT INTO countries VALUES( 202, 'Swaziland', 'SZ', 'SWZ',  1);
INSERT INTO countries VALUES( 203, 'Sweden', 'SE', 'SWE',  5);
INSERT INTO countries VALUES( 204, 'Switzerland', 'CH', 'CHE',  5);
INSERT INTO countries VALUES( 205, 'Syrian Arab Republic', 'SY', 'SYR',  1);
INSERT INTO countries VALUES( 206, 'Taiwan', 'TW', 'TWN',  8);
INSERT INTO countries VALUES( 207, 'Tajikistan', 'TJ', 'TJK',  1);
INSERT INTO countries VALUES( 208, 'Tanzania, United Republic of', 'TZ', 'TZA',  1);
INSERT INTO countries VALUES( 209, 'Thailand', 'TH', 'THA',  1);
INSERT INTO countries VALUES( 210, 'Togo', 'TG', 'TGO',  1);
INSERT INTO countries VALUES( 211, 'Tokelau', 'TK', 'TKL',  1);
INSERT INTO countries VALUES( 212, 'Tonga', 'TO', 'TON',  1);
INSERT INTO countries VALUES( 213, 'Trinidad and Tobago', 'TT', 'TTO',  1);
INSERT INTO countries VALUES( 214, 'Tunisia', 'TN', 'TUN',  1);
INSERT INTO countries VALUES( 215, 'Turkey', 'TR', 'TUR',  1);
INSERT INTO countries VALUES( 216, 'Turkmenistan', 'TM', 'TKM',  1);
INSERT INTO countries VALUES( 217, 'Turks and Caicos Islands', 'TC', 'TCA',  1);
INSERT INTO countries VALUES( 218, 'Tuvalu', 'TV', 'TUV',  1);
INSERT INTO countries VALUES( 219, 'Uganda', 'UG', 'UGA',  1);
INSERT INTO countries VALUES( 220, 'Ukraine', 'UA', 'UKR',  1);
INSERT INTO countries VALUES( 221, 'United Arab Emirates', 'AE', 'ARE',  1);
INSERT INTO countries VALUES( 222, 'United Kingdom', 'GB', 'GBR',  11);
INSERT INTO countries VALUES( 223, 'United States', 'US', 'USA',  2);
INSERT INTO countries VALUES( 224, 'United States Minor Outlying Islands', 'UM', 'UMI',  1);
INSERT INTO countries VALUES( 225, 'Uruguay', 'UY', 'URY',  1);
INSERT INTO countries VALUES( 226, 'Uzbekistan', 'UZ', 'UZB',  1);
INSERT INTO countries VALUES( 227, 'Vanuatu', 'VU', 'VUT',  1);
INSERT INTO countries VALUES( 228, 'Vatican City State (Holy See)', 'VA', 'VAT',  1);
INSERT INTO countries VALUES( 229, 'Venezuela', 'VE', 'VEN',  1);
INSERT INTO countries VALUES( 230, 'Viet Nam', 'VN', 'VNM',  1);
INSERT INTO countries VALUES( 231, 'Virgin Islands (British)', 'VG', 'VGB',  1);
INSERT INTO countries VALUES( 232, 'Virgin Islands (U.S.)', 'VI', 'VIR',  1);
INSERT INTO countries VALUES( 233, 'Wallis and Futuna Islands', 'WF', 'WLF',  1);
INSERT INTO countries VALUES( 234, 'Western Sahara', 'EH', 'ESH',  1);
INSERT INTO countries VALUES( 235, 'Yemen', 'YE', 'YEM',  1);
INSERT INTO countries VALUES( 236, 'Yugoslavia', 'YU', 'YUG',  1);
INSERT INTO countries VALUES( 237, 'Zaire', 'ZR', 'ZAR',  1);
INSERT INTO countries VALUES( 238, 'Zambia', 'ZM', 'ZMB',  1);
INSERT INTO countries VALUES( 239, 'Zimbabwe', 'ZW', 'ZWE',  1);


#
# Data for table: currencies
#
INSERT INTO currencies VALUES( 1, 'US Dollar', 'USD', '$', '', '.', ',', '2', '1.00000000', '2004-04-05 08:33:25');
INSERT INTO currencies VALUES( 2, 'Euro', 'EUR', '&euro;', '', '.', ',', '2', '0.82529998', '2004-04-05 08:33:25');
INSERT INTO currencies VALUES( 3, 'British Pound', 'GBP', '&pound;', '', '.', ',', '2', '0.54670000', '2004-04-05 08:33:25');


#
# Data for table: customers
# 
INSERT INTO `customers` VALUES (1, 0, 'm', 'Sal', 'Iozzia', '0000-00-00 00:00:00', 'sal@loadedcommerce.com', 1, 'f6ffd4179cb5a2dff4781fc366529738:52', '1', NULL, '', 1, '');


#
# Data for table: customers_info
#
INSERT INTO `customers_info` VALUES (1, '2012-07-05 15:30:38', 1, '2012-07-05 15:25:10', '2012-07-05 15:31:23', 0);


#
# Data for table: geo_zones
#


#
# Data for table: infobox_configuration
#
INSERT INTO infobox_configuration VALUES( 9,  1, 'downloads.php', 'BOX_HEADING_DOWNLOADS', 'no', 'right',  8, '0000-00-00 00:00:00', now(), 'You Have a Download', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  2, 'currencies.php', 'BOX_HEADING_CURRENCIES', 'no', 'right',  7, '0000-00-00 00:00:00', now(), 'Currencies', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  3, 'order_history.php', 'BOX_HEADING_CUSTOMER_ORDERS', 'no', 'right',  5, '0000-00-00 00:00:00', now(), 'Order History', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  4, 'languages.php', 'BOX_HEADING_LANGUAGES', 'no', 'right',  6, '0000-00-00 00:00:00', now(), 'Languages', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  5, 'best_sellers.php', 'BOX_HEADING_BESTSELLERS', 'no', 'right',  4, '0000-00-00 00:00:00', now(), 'Best Sellers', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  6, 'customer_gv.php', 'BOX_HEADING_GIFT_VOUCHER', 'no', 'right',  2, '0000-00-00 00:00:00', now(), 'Gift Voucher', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  7, 'loginbox.php', 'BOX_HEADING_LOGIN', 'no', 'right',  3, '0000-00-00 00:00:00', now(), 'Your Account', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  8, 'shopping_cart.php', 'BOX_HEADING_SHOPPING_CART', 'yes', 'right',  1, '0000-00-00 00:00:00', now(), 'Shopping Cart', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  9, 'googlead.php', 'BOX_GOOGLE_AD_BANNER_HEADING', 'no', 'left',  23, '0000-00-00 00:00:00', now(), 'Google Ad', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  10, 'whos_online.php', 'BOX_HEADING_WHOS_ONLINE', 'no', 'left',  22, '0000-00-00 00:00:00', now(), 'Who\'s Online', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  11, 'links.php', 'BOX_HEADING_LINKS', 'no', 'left',  21, '0000-00-00 00:00:00', now(), 'Links', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  12, 'featured.php', 'BOX_HEADING_FEATURED', 'no', 'left',  19, '0000-00-00 00:00:00', now(), 'Featured', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  13, 'affiliate.php', 'BOX_HEADING_AFFILIATE', 'no', 'left',  20, '0000-00-00 00:00:00', now(), 'Affiliate Info', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  14, 'shop_by_price.php', 'BOX_HEADING_SHOP_BY_PRICE', 'no', 'left',  18, '0000-00-00 00:00:00', now(), 'Shop by Price', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  15, 'whats_new.php', 'BOX_HEADING_WHATS_NEW', 'no', 'left',  17, '0000-00-00 00:00:00', now(), 'Latest products', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  16, 'tell_a_friend.php', 'BOX_HEADING_TELL_A_FRIEND', 'no', 'left',  16, '0000-00-00 00:00:00', now(), 'Tell A Friend', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  17, 'product_notifications.php', 'BOX_HEADING_NOTIFICATIONS', 'no', 'left',  15, '0000-00-00 00:00:00', now(), 'Notifications', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  18, 'manufacturer_info.php', 'BOX_HEADING_MANUFACTURER_INFO', 'no', 'left',  14, '0000-00-00 00:00:00', now(), 'Manufacturers Info', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  19, 'manufacturers.php', 'BOX_HEADING_MANUFACTURERS', 'no', 'left',  13, '0000-00-00 00:00:00', now(), 'Manufacturers', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  20, 'search.php', 'BOX_HEADING_SEARCH', 'no', 'left',  12, '0000-00-00 00:00:00', now(), 'Quick Find', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  21, 'reviews.php', 'BOX_HEADING_REVIEWS', 'no', 'left',  6, '0000-00-00 00:00:00', now(), 'Reviews', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  22, 'specials.php', 'BOX_HEADING_SPECIALS', 'yes', 'left',  7, '0000-00-00 00:00:00', now(), 'Specials', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  23, 'categories3.php', 'BOX_HEADING_CATEGORIES3', 'no', 'left',  4, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  24, 'categories4.php', 'BOX_HEADING_CATEGORIES4', 'yes', 'left',  5, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  25, 'categories1.php', 'BOX_HEADING_CATEGORIES1', 'no', 'left',  4, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  26, 'categories2.php', 'BOX_HEADING_CATEGORIES2', 'no', 'left',  4, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  27, 'categories.php', 'BOX_HEADING_CATEGORIES', 'no', 'left',  4, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  28, 'articles.php', 'BOX_HEADING_ARTICLES', 'no', 'left',  24, '0000-00-00 00:00:00', now(), 'Articles', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  30, 'faq.php', 'BOX_HEADING_FAQ', 'no', 'left',  27, '0000-00-00 00:00:00', now(), 'Faq', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  31, 'authors.php', 'BOX_HEADING_AUTHORS', 'no', 'left',  26, '0000-00-00 00:00:00', now(), 'Authors', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  32, 'asearch.php', 'BOX_HEADING_ASEARCH', 'no', 'left',  28, '0000-00-00 00:00:00', now(), 'Article Search', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  33, 'wishlist.php', 'BOX_HEADING_WISHLIST', 'no', 'right',  10, '0000-00-00 00:00:00', now(), 'Wishlist', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  34, 'boxad.php', 'BOX_AD_LP_HEADING', 'yes', 'right',  11, '0000-00-00 00:00:00', now(), 'Loaded Payments', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  35, 'search1.php', 'BOX_HEADING_SEARCH1', 'no', 'right',  9, '0000-00-00 00:00:00', now(), 'Advanced Search', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 9,  36, 'buysafe.php', 'BOX_HEADING_BUYSAFE', 'no', 'left',  8, '0000-00-00 00:00:00', now(), '', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 9,  37, 'example.php', 'BOX_HEADING_EXAMPLE', 'no', 'left',  9, '0000-00-00 00:00:00', now(), 'Example', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 9,  38, 'we_accept.php', 'BOX_HEADING_WE_ACCEPT', 'no', 'left',  10, '0000-00-00 00:00:00', now(), 'Cards We Accept', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 9,  39, 'pages.php', 'BOX_HEADING_PAGES', 'no', 'left',  11, '0000-00-00 00:00:00', now(), 'Information', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  40, 'downloads.php', 'BOX_HEADING_DOWNLOADS', 'no', 'right',  7, '0000-00-00 00:00:00', now(), 'You Have a Download', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  41, 'currencies.php', 'BOX_HEADING_CURRENCIES', 'no', 'right',  6, '0000-00-00 00:00:00', now(), 'Currencies', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  42, 'order_history.php', 'BOX_HEADING_CUSTOMER_ORDERS', 'no', 'right',  4, '0000-00-00 00:00:00', now(), 'Order History', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  43, 'languages.php', 'BOX_HEADING_LANGUAGES', 'no', 'right',  5, '0000-00-00 00:00:00', now(), 'Languages', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  44, 'best_sellers.php', 'BOX_HEADING_BESTSELLERS', 'no', 'right',  3, '0000-00-00 00:00:00', now(), 'Best Sellers', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  45, 'customer_gv.php', 'BOX_HEADING_GIFT_VOUCHER', 'no', 'right',  1, '0000-00-00 00:00:00', now(), 'Gift Voucher', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  46, 'loginbox.php', 'BOX_HEADING_LOGIN', 'yes', 'right',  2, '0000-00-00 00:00:00', now(), 'Your Account', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  47, 'shopping_cart.php', 'BOX_HEADING_SHOPPING_CART', 'yes', 'right',  1, '0000-00-00 00:00:00', now(), 'Shopping Cart', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  48, 'googlead.php', 'BOX_GOOGLE_AD_BANNER_HEADING', 'no', 'left',  26, '0000-00-00 00:00:00', now(), 'Google Ad', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  49, 'whos_online.php', 'BOX_HEADING_WHOS_ONLINE', 'no', 'left',  25, '0000-00-00 00:00:00', now(), 'Who\'s Online', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  50, 'links.php', 'BOX_HEADING_LINKS', 'no', 'left',  24, '0000-00-00 00:00:00', now(), 'Links', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  51, 'featured.php', 'BOX_HEADING_FEATURED', 'no', 'left',  22, '0000-00-00 00:00:00', now(), 'Featured', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  52, 'affiliate.php', 'BOX_HEADING_AFFILIATE', 'no', 'left',  23, '0000-00-00 00:00:00', now(), 'Affiliate Info', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  53, 'shop_by_price.php', 'BOX_HEADING_SHOP_BY_PRICE', 'no', 'left',  21, '0000-00-00 00:00:00', now(), 'Shop by Price', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  54, 'whats_new.php', 'BOX_HEADING_WHATS_NEW', 'no', 'left',  20, '0000-00-00 00:00:00', now(), 'Latest products', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  55, 'tell_a_friend.php', 'BOX_HEADING_TELL_A_FRIEND', 'no', 'left',  19, '0000-00-00 00:00:00', now(), 'Tell A Friend', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  56, 'product_notifications.php', 'BOX_HEADING_NOTIFICATIONS', 'no', 'left',  18, '0000-00-00 00:00:00', now(), 'Notifications', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  57, 'manufacturer_info.php', 'BOX_HEADING_MANUFACTURER_INFO', 'no', 'left',  17, '0000-00-00 00:00:00', now(), 'Manufacturers Info', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  58, 'manufacturers.php', 'BOX_HEADING_MANUFACTURERS', 'no', 'left',  16, '0000-00-00 00:00:00', now(), 'Manufacturers', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  59, 'search.php', 'BOX_HEADING_SEARCH', 'no', 'left',  15, '0000-00-00 00:00:00', now(), 'Quick Find', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  60, 'reviews.php', 'BOX_HEADING_REVIEWS', 'no', 'left',  9, '0000-00-00 00:00:00', now(), 'Reviews', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  61, 'specials.php', 'BOX_HEADING_SPECIALS', 'yes', 'left',  10, '0000-00-00 00:00:00', now(), 'Specials', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  62, 'categories3.php', 'BOX_HEADING_CATEGORIES3', 'no', 'left',  7, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  63, 'categories4.php', 'BOX_HEADING_CATEGORIES4', 'no', 'left',  8, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  64, 'categories1.php', 'BOX_HEADING_CATEGORIES1', 'no', 'left',  5, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  65, 'categories2.php', 'BOX_HEADING_CATEGORIES2', 'no', 'left',  6, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  66, 'categories.php', 'BOX_HEADING_CATEGORIES', 'yes', 'left',  1, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  67, 'articles.php', 'BOX_HEADING_ARTICLES', 'no', 'left',  27, '0000-00-00 00:00:00', now(), 'Articles', 'infobox', '#F39800'); 
INSERT INTO infobox_configuration VALUES( 11,  69, 'faq.php', 'BOX_HEADING_FAQ', 'no', 'left',  30, '0000-00-00 00:00:00', now(), 'Faq', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  70, 'authors.php', 'BOX_HEADING_AUTHORS', 'no', 'left',  29, '0000-00-00 00:00:00', now(), 'Authors', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  71, 'asearch.php', 'BOX_HEADING_ASEARCH', 'no', 'left',  31, '0000-00-00 00:00:00', now(), 'Article Search', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  72, 'wishlist.php', 'BOX_HEADING_WISHLIST', 'no', 'right',  9, '0000-00-00 00:00:00', now(), 'Wishlist', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  73, 'boxad.php', 'BOX_AD_LP_HEADING', 'yes', 'left',  10, '0000-00-00 00:00:00', now(), 'Loaded Payments', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  74, 'search1.php', 'BOX_HEADING_SEARCH1', 'no', 'right',  8, '0000-00-00 00:00:00', now(), 'Advanced Search', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  75, 'buysafe.php', 'BOX_HEADING_BUYSAFE', 'no', 'left',  14, '0000-00-00 00:00:00', now(), '', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  76, 'example.php', 'BOX_HEADING_EXAMPLE', 'no', 'left',  13, '0000-00-00 00:00:00', now(), 'Example', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  77, 'we_accept.php', 'BOX_HEADING_WE_ACCEPT', 'no', 'left',  12, '0000-00-00 00:00:00', now(), 'Cards We Accept', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  78, 'pages.php', 'BOX_HEADING_PAGES', 'yes', 'left',  11, '0000-00-00 00:00:00', now(), 'Information', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 11,  80, 'chatstat.php', 'BOX_HEADING_CHATSTAT', 'no', 'left',  3, '0000-00-00 00:00:00', now(), '', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 11,  81, 'controlscan.php', 'BOX_HEADING_CONTROLSCAN', 'no', 'left',  4, '0000-00-00 00:00:00', now(), '', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 11,  82, 'best_sellers_scroll.php', 'BOX_HEADING_BESTSELLER_SCROLL', 'no', 'left',  32, '0000-00-00 00:00:00', now(), '', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 11,  83, 'affiliate_branding.php', 'BOX_HEADING_AFFILIATE', 'no', 'left',  33, '0000-00-00 00:00:00', now(), '', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 11,  84, 'fdm_file_library.php', 'BOX_HEADING_FDMS', 'no', 'left',  34, '0000-00-00 00:00:00', now(), '', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 11,  85, 'forms.php', 'BOX_HEADING_FORMS', 'no', 'left',  35, '0000-00-00 00:00:00', now(), '', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 12,  86, 'downloads.php', 'BOX_HEADING_DOWNLOADS', 'no', 'right',  7, '0000-00-00 00:00:00', now(), 'You Have a Download', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  87, 'currencies.php', 'BOX_HEADING_CURRENCIES', 'no', 'right',  6, '0000-00-00 00:00:00', now(), 'Currencies', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  88, 'order_history.php', 'BOX_HEADING_CUSTOMER_ORDERS', 'no', 'right',  4, '0000-00-00 00:00:00', now(), 'Order History', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  89, 'languages.php', 'BOX_HEADING_LANGUAGES', 'no', 'right',  5, '0000-00-00 00:00:00', now(), 'Languages', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  90, 'best_sellers.php', 'BOX_HEADING_BESTSELLERS', 'no', 'right',  3, '0000-00-00 00:00:00', now(), 'Best Sellers', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  91, 'customer_gv.php', 'BOX_HEADING_GIFT_VOUCHER', 'no', 'right',  1, '0000-00-00 00:00:00', now(), 'Gift Voucher', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  92, 'loginbox.php', 'BOX_HEADING_LOGIN', 'yes', 'right',  2, '0000-00-00 00:00:00', now(), 'Your Account', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  93, 'shopping_cart.php', 'BOX_HEADING_SHOPPING_CART', 'yes', 'right',  1, '0000-00-00 00:00:00', now(), 'Shopping Cart', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  94, 'googlead.php', 'BOX_GOOGLE_AD_BANNER_HEADING', 'no', 'left',  26, '0000-00-00 00:00:00', now(), 'Google Ad', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  95, 'whos_online.php', 'BOX_HEADING_WHOS_ONLINE', 'no', 'left',  25, '0000-00-00 00:00:00', now(), 'Who\'s Online', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  96, 'links.php', 'BOX_HEADING_LINKS', 'no', 'left',  24, '0000-00-00 00:00:00', now(), 'Links', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  97, 'featured.php', 'BOX_HEADING_FEATURED', 'no', 'left',  22, '0000-00-00 00:00:00', now(), 'Featured', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  98, 'affiliate.php', 'BOX_HEADING_AFFILIATE', 'no', 'left',  23, '0000-00-00 00:00:00', now(), 'Affiliate Info', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  99, 'shop_by_price.php', 'BOX_HEADING_SHOP_BY_PRICE', 'no', 'left',  21, '0000-00-00 00:00:00', now(), 'Shop by Price', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  100, 'whats_new.php', 'BOX_HEADING_WHATS_NEW', 'no', 'left',  20, '0000-00-00 00:00:00', now(), 'Latest products', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  101, 'tell_a_friend.php', 'BOX_HEADING_TELL_A_FRIEND', 'no', 'left',  19, '0000-00-00 00:00:00', now(), 'Tell A Friend', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  102, 'product_notifications.php', 'BOX_HEADING_NOTIFICATIONS', 'no', 'left',  18, '0000-00-00 00:00:00', now(), 'Notifications', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  103, 'manufacturer_info.php', 'BOX_HEADING_MANUFACTURER_INFO', 'no', 'left',  17, '0000-00-00 00:00:00', now(), 'Manufacturers Info', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  104, 'manufacturers.php', 'BOX_HEADING_MANUFACTURERS', 'no', 'left',  16, '0000-00-00 00:00:00', now(), 'Manufacturers', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  105, 'search.php', 'BOX_HEADING_SEARCH', 'no', 'left',  15, '0000-00-00 00:00:00', now(), 'Quick Find', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  106, 'reviews.php', 'BOX_HEADING_REVIEWS', 'no', 'left',  9, '0000-00-00 00:00:00', now(), 'Reviews', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  107, 'specials.php', 'BOX_HEADING_SPECIALS', 'yes', 'left',  10, '0000-00-00 00:00:00', now(), 'Specials', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  108, 'categories3.php', 'BOX_HEADING_CATEGORIES3', 'no', 'left',  7, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  109, 'categories4.php', 'BOX_HEADING_CATEGORIES4', 'no', 'left',  8, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  110, 'categories1.php', 'BOX_HEADING_CATEGORIES1', 'no', 'left',  5, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  111, 'categories2.php', 'BOX_HEADING_CATEGORIES2', 'no', 'left',  6, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  112, 'categories.php', 'BOX_HEADING_CATEGORIES', 'yes', 'left',  1, '0000-00-00 00:00:00', now(), 'Categories', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  113, 'articles.php', 'BOX_HEADING_ARTICLES', 'no', 'left',  27, '0000-00-00 00:00:00', now(), 'Articles', 'infobox', '#F39800'); 
INSERT INTO infobox_configuration VALUES( 12,  114, 'faq.php', 'BOX_HEADING_FAQ', 'no', 'left',  30, '0000-00-00 00:00:00', now(), 'Faq', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  115, 'authors.php', 'BOX_HEADING_AUTHORS', 'no', 'left',  29, '0000-00-00 00:00:00', now(), 'Authors', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  116, 'asearch.php', 'BOX_HEADING_ASEARCH', 'no', 'left',  31, '0000-00-00 00:00:00', now(), 'Article Search', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  117, 'wishlist.php', 'BOX_HEADING_WISHLIST', 'no', 'right',  9, '0000-00-00 00:00:00', now(), 'Wishlist', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  118, 'boxad.php', 'BOX_AD_LP_HEADING', 'yes', 'left',  10, '0000-00-00 00:00:00', now(), 'Loaded Payments', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  119, 'search1.php', 'BOX_HEADING_SEARCH1', 'no', 'right',  8, '0000-00-00 00:00:00', now(), 'Advanced Search', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  120, 'buysafe.php', 'BOX_HEADING_BUYSAFE', 'no', 'left',  14, '0000-00-00 00:00:00', now(), '', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  121, 'example.php', 'BOX_HEADING_EXAMPLE', 'no', 'left',  13, '0000-00-00 00:00:00', now(), 'Example', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  122, 'we_accept.php', 'BOX_HEADING_WE_ACCEPT', 'no', 'left',  12, '0000-00-00 00:00:00', now(), 'Cards We Accept', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  123, 'pages.php', 'BOX_HEADING_PAGES', 'yes', 'left',  11, '0000-00-00 00:00:00', now(), 'Information', 'infobox', '#F39800');
INSERT INTO infobox_configuration VALUES( 12,  124, 'chatstat.php', 'BOX_HEADING_CHATSTAT', 'no', 'left',  3, '0000-00-00 00:00:00', now(), '', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 12,  125, 'controlscan.php', 'BOX_HEADING_CONTROLSCAN', 'no', 'left',  4, '0000-00-00 00:00:00', now(), '', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 12,  126, 'best_sellers_scroll.php', 'BOX_HEADING_BESTSELLER_SCROLL', 'no', 'left',  32, '0000-00-00 00:00:00', now(), '', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 12,  127, 'affiliate_branding.php', 'BOX_HEADING_AFFILIATE', 'no', 'left',  33, '0000-00-00 00:00:00', now(), '', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 12,  128, 'fdm_file_library.php', 'BOX_HEADING_FDMS', 'no', 'left',  34, '0000-00-00 00:00:00', now(), '', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES( 12,  129, 'forms.php', 'BOX_HEADING_FORMS', 'no', 'left',  35, '0000-00-00 00:00:00', now(), '', 'infobox', '#FFFFFF');


#
# Data for table: infobox_heading
#
INSERT INTO infobox_heading VALUES( 1,  1, 'You Have a Download');
INSERT INTO infobox_heading VALUES( 2,  1, 'Currencies');
INSERT INTO infobox_heading VALUES( 3,  1, 'Order History');
INSERT INTO infobox_heading VALUES( 4,  1, 'Languages');
INSERT INTO infobox_heading VALUES( 5,  1, 'Best Sellers');
INSERT INTO infobox_heading VALUES( 6,  1, 'Gift Voucher');
INSERT INTO infobox_heading VALUES( 7,  1, 'Your Account');
INSERT INTO infobox_heading VALUES( 8,  1, 'Shopping Cart');
INSERT INTO infobox_heading VALUES( 9,  1, 'Google Ad');
INSERT INTO infobox_heading VALUES( 10,  1, 'Who\'s Online');
INSERT INTO infobox_heading VALUES( 11,  1, 'Links');
INSERT INTO infobox_heading VALUES( 12,  1, 'Featured');
INSERT INTO infobox_heading VALUES( 13,  1, 'Affiliate Info');
INSERT INTO infobox_heading VALUES( 14,  1, 'Shop by Price');
INSERT INTO infobox_heading VALUES( 15,  1, 'Latest products');
INSERT INTO infobox_heading VALUES( 16,  1, 'Tell A Friend');
INSERT INTO infobox_heading VALUES( 17,  1, 'Notifications');
INSERT INTO infobox_heading VALUES( 18,  1, 'Manufacturers Info');
INSERT INTO infobox_heading VALUES( 19,  1, 'Manufacturers');
INSERT INTO infobox_heading VALUES( 20,  1, 'Quick Find');
INSERT INTO infobox_heading VALUES( 21,  1, 'Reviews');
INSERT INTO infobox_heading VALUES( 22,  1, 'Specials');
INSERT INTO infobox_heading VALUES( 23,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 24,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 25,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 26,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 27,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 28,  1, 'Articles');
INSERT INTO infobox_heading VALUES( 30,  1, 'Faq');
INSERT INTO infobox_heading VALUES( 31,  1, 'Authors');
INSERT INTO infobox_heading VALUES( 32,  1, 'Article Search');
INSERT INTO infobox_heading VALUES( 33,  1, 'Wishlist');
INSERT INTO infobox_heading VALUES( 34,  1, 'Loaded Payments');
INSERT INTO infobox_heading VALUES( 35,  1, 'Advanced Search');
INSERT INTO infobox_heading VALUES( 36,  1, '');
INSERT INTO infobox_heading VALUES( 37,  1, 'Example');
INSERT INTO infobox_heading VALUES( 38,  1, 'Cards We Accept');
INSERT INTO infobox_heading VALUES( 39,  1, 'Information');
INSERT INTO infobox_heading VALUES( 40,  1, 'You Have a Download');
INSERT INTO infobox_heading VALUES( 41,  1, 'Currencies');
INSERT INTO infobox_heading VALUES( 42,  1, 'Order History');
INSERT INTO infobox_heading VALUES( 43,  1, 'Languages');
INSERT INTO infobox_heading VALUES( 44,  1, 'Best Sellers');
INSERT INTO infobox_heading VALUES( 45,  1, 'Gift Voucher');
INSERT INTO infobox_heading VALUES( 46,  1, 'Your Account');
INSERT INTO infobox_heading VALUES( 47,  1, 'Shopping Cart');
INSERT INTO infobox_heading VALUES( 48,  1, 'Google Ad');
INSERT INTO infobox_heading VALUES( 49,  1, 'Who\'s Online');
INSERT INTO infobox_heading VALUES( 50,  1, 'Links');
INSERT INTO infobox_heading VALUES( 51,  1, 'Featured');
INSERT INTO infobox_heading VALUES( 52,  1, 'Affiliate Info');
INSERT INTO infobox_heading VALUES( 53,  1, 'Shop by Price');
INSERT INTO infobox_heading VALUES( 54,  1, 'Latest products');
INSERT INTO infobox_heading VALUES( 55,  1, 'Tell A Friend');
INSERT INTO infobox_heading VALUES( 56,  1, 'Notifications');
INSERT INTO infobox_heading VALUES( 57,  1, 'Manufacturers Info');
INSERT INTO infobox_heading VALUES( 58,  1, 'Manufacturers');
INSERT INTO infobox_heading VALUES( 59,  1, 'Quick Find');
INSERT INTO infobox_heading VALUES( 60,  1, 'Reviews');
INSERT INTO infobox_heading VALUES( 61,  1, 'Specials');
INSERT INTO infobox_heading VALUES( 62,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 63,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 64,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 65,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 66,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 67,  1, 'Articles'); 
INSERT INTO infobox_heading VALUES( 69,  1, 'Faq');
INSERT INTO infobox_heading VALUES( 70,  1, 'Authors');
INSERT INTO infobox_heading VALUES( 71,  1, 'Article Search');
INSERT INTO infobox_heading VALUES( 72,  1, 'Wishlist');
INSERT INTO infobox_heading VALUES( 73,  1, 'Loaded Payments');
INSERT INTO infobox_heading VALUES( 74,  1, 'Advanced Search');
INSERT INTO infobox_heading VALUES( 75,  1, '');
INSERT INTO infobox_heading VALUES( 76,  1, 'Example');
INSERT INTO infobox_heading VALUES( 77,  1, 'Cards We Accept');
INSERT INTO infobox_heading VALUES( 78,  1, 'Information');
INSERT INTO infobox_heading VALUES( 80,  1, 'Chat Stat');
INSERT INTO infobox_heading VALUES( 81,  1, 'Control Scan');
INSERT INTO infobox_heading VALUES( 82,  1, 'Best Sellers');
INSERT INTO infobox_heading VALUES( 83,  1, 'Affiliate Branding');
INSERT INTO infobox_heading VALUES( 84,  1, 'FDMS');
INSERT INTO infobox_heading VALUES( 85,  1, 'Forms and Surveys');
INSERT INTO infobox_heading VALUES( 86,  1, 'You Have a Download');
INSERT INTO infobox_heading VALUES( 87,  1, 'Currencies');
INSERT INTO infobox_heading VALUES( 88,  1, 'Order History');
INSERT INTO infobox_heading VALUES( 89,  1, 'Languages');
INSERT INTO infobox_heading VALUES( 90,  1, 'Best Sellers');
INSERT INTO infobox_heading VALUES( 91,  1, 'Gift Voucher');
INSERT INTO infobox_heading VALUES( 92,  1, 'Your Account');
INSERT INTO infobox_heading VALUES( 93,  1, 'Shopping Cart');
INSERT INTO infobox_heading VALUES( 94,  1, 'Google Ad');
INSERT INTO infobox_heading VALUES( 95,  1, 'Who\'s Online');
INSERT INTO infobox_heading VALUES( 96,  1, 'Links');
INSERT INTO infobox_heading VALUES( 97,  1, 'Featured');
INSERT INTO infobox_heading VALUES( 98,  1, 'Affiliate Info');
INSERT INTO infobox_heading VALUES( 99,  1, 'Shop by Price');
INSERT INTO infobox_heading VALUES( 100,  1, 'Latest products');
INSERT INTO infobox_heading VALUES( 101,  1, 'Tell A Friend');
INSERT INTO infobox_heading VALUES( 102,  1, 'Notifications');
INSERT INTO infobox_heading VALUES( 103,  1, 'Manufacturers Info');
INSERT INTO infobox_heading VALUES( 104,  1, 'Manufacturers');
INSERT INTO infobox_heading VALUES( 105,  1, 'Quick Find');
INSERT INTO infobox_heading VALUES( 106,  1, 'Reviews');
INSERT INTO infobox_heading VALUES( 107,  1, 'Specials');
INSERT INTO infobox_heading VALUES( 108,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 109,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 110,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 111,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 112,  1, 'Categories');
INSERT INTO infobox_heading VALUES( 113,  1, 'Articles'); 
INSERT INTO infobox_heading VALUES( 114,  1, 'Faq');
INSERT INTO infobox_heading VALUES( 115,  1, 'Authors');
INSERT INTO infobox_heading VALUES( 116,  1, 'Article Search');
INSERT INTO infobox_heading VALUES( 117,  1, 'Wishlist');
INSERT INTO infobox_heading VALUES( 118,  1, 'Loaded Payments');
INSERT INTO infobox_heading VALUES( 119,  1, 'Advanced Search');
INSERT INTO infobox_heading VALUES( 120,  1, '');
INSERT INTO infobox_heading VALUES( 121,  1, 'Example');
INSERT INTO infobox_heading VALUES( 122,  1, 'Cards We Accept');
INSERT INTO infobox_heading VALUES( 123,  1, 'Information');
INSERT INTO infobox_heading VALUES( 124,  1, 'Chat Stat');
INSERT INTO infobox_heading VALUES( 125,  1, 'Control Scan');
INSERT INTO infobox_heading VALUES( 126,  1, 'Best Sellers');
INSERT INTO infobox_heading VALUES( 127,  1, 'Affiliate Branding');
INSERT INTO infobox_heading VALUES( 128,  1, 'FDMS');
INSERT INTO infobox_heading VALUES( 129,  1, 'Forms and Surveys');

#
# Data for table: languages
#
INSERT INTO languages VALUES( 1, 'English', 'en', 'icon.gif', 'english',  1);


#
# Data for table: links_status
#
INSERT INTO links_status VALUES( 1,  1, 'Pending');
INSERT INTO links_status VALUES( 2,  1, 'Approved');
INSERT INTO links_status VALUES( 3,  1, 'Disabled');


#
# Data for table: orders_status
#
INSERT INTO orders_status VALUES( 1,  1, 'Pending');
INSERT INTO orders_status VALUES( 2,  1, 'Processing');
INSERT INTO orders_status VALUES( 3,  1, 'Shipped');
INSERT INTO orders_status VALUES( 4,  1, 'Delivered');
INSERT INTO orders_status VALUES( 5,  1, 'Allow Download');
INSERT INTO orders_status VALUES( 6,  1, 'On Hold');
INSERT INTO orders_status VALUES( 7,  1, 'Canceled');
INSERT INTO orders_status VALUES( 8,  1, 'Awaiting CC Processing');
INSERT INTO orders_status VALUES( 88888,  1, 'Abandoned Shopping Cart');
INSERT INTO orders_status VALUES( 99999,  1, 'Paypal Processing');


     #
# Data for table: pages
#
INSERT INTO pages VALUES( 1, 'header_account.gif', '2008-08-04 14:39:45', '2008-08-04 14:39:45', 'System',  1,  10,  1,  2, '', '', '',  0, 'G,0');
INSERT INTO pages VALUES( 2, 'header_account.gif', '2008-08-04 14:39:26', '0000-00-00 00:00:00', 'System',  1,  9999,  1,  2, '', '', '',  0, 'G,0');
INSERT INTO pages VALUES( 3, 'header_account.gif', '2008-08-04 14:39:32', '0000-00-00 00:00:00', 'System',  1,  9999,  1,  2, '', '', '',  0, 'G,0');


#
# Data for table: pages_categories
#
INSERT INTO pages_categories VALUES( 1, 'header_acouunt.gif',  10, '0000-00-00 00:00:00', '0000-00-00 00:00:00',  1,  0,  0, '', '', '', '',  0,  0,  0,  1,  1,  0, '',  0, 'G,0');
INSERT INTO pages_categories VALUES( 2, '',  20, '2008-07-08 21:00:51', '2008-07-08 21:07:44',  1,  0,  1, 'contact_us.php', '', '', '',  1,  0,  2,  1,  0,  0, '',  0, 'G,0');


#
# Data for table: pages_categories_description
#
INSERT INTO pages_categories_description VALUES( 1,  1, 'Information Pages', 'Information Pages', 'Information Pages', 'Information Pages', 'Information Pages', 'Information Pages', 'Information Pages', 'Information Pages');
INSERT INTO pages_categories_description VALUES( 2,  1, 'Contact Us', '', 'Contact Us', '', '', '', '', '');


#
# Data for table: pages_description
#
INSERT INTO pages_description VALUES( 1,  1, 'Terms and Conditions', 'Terms and Conditions', 'Terms and Conditions', 'Terms and Conditions', 'This is the terms and conditions blurb.', 'This is the terms and conditions description.', 'Terms and Conditions', '');
INSERT INTO pages_description VALUES( 2,  1, 'Privacy Policy', 'Privacy Policy', 'Privacy Policy', 'Privacy Policy', 'This is the privacy policy blurb.', 'This is the privacy policy description.', 'Privacy Policy', '');
INSERT INTO pages_description VALUES( 3,  1, 'Shipping Policy', 'Shipping Policy', 'Shipping Policy', 'Shipping Policy', 'This is the shipping policy blurb.', 'This is the shipping policy description.', 'Shipping Policy', '');


#
# Data for table: pages_to_categories
#
INSERT INTO pages_to_categories VALUES( 1,  1,  10);
INSERT INTO pages_to_categories VALUES( 2,  1,  20);
INSERT INTO pages_to_categories VALUES( 3,  1,  30);


#
# Data for table: template
#
INSERT INTO template VALUES( 9, 'Original_ats', now(), '0000-00-00 00:00:00', 'Original.gif', '3', '8', '3', '3', '100%', 'yes', 'yes', '130', '130', 'yes', '1', 'yes', 'no', 'no', 'yes', 'mainpage.php', 'featured.php', '', '', '', '', 'yes', '', '', '',  1,  1);
INSERT INTO template VALUES( 11, 'cre65_ats', now(), '0000-00-00 00:00:00', 'preview.gif', '0', '5', '0', '0', '980', 'yes', 'yes', '194', '194', 'yes', '1', 'yes', 'no', 'no', 'yes', 'mainpage.php', '', '', '', '', '', 'yes', '', '', '',  1,  1);
INSERT INTO template VALUES( 12, 'sevenofsix', now(), '0000-00-00 00:00:00', 'sevenofsix.gif', '0', '5', '0', '0', '980', 'yes', 'yes', '2', '2', 'yes', '1', 'yes', 'no', 'no', 'yes', 'mainpage.php', 'new_products.php', '', '', '', '', 'yes', '', '', '',  1,  1);


#
# Data for table: zones
#
INSERT INTO zones VALUES( 1,  223, 'AL', 'Alabama');
INSERT INTO zones VALUES( 2,  223, 'AK', 'Alaska');
INSERT INTO zones VALUES( 3,  223, 'AS', 'American Samoa');
INSERT INTO zones VALUES( 4,  223, 'AZ', 'Arizona');
INSERT INTO zones VALUES( 5,  223, 'AR', 'Arkansas');
INSERT INTO zones VALUES( 6,  223, 'AF', 'Armed Forces Africa');
INSERT INTO zones VALUES( 7,  223, 'AA', 'Armed Forces Americas');
INSERT INTO zones VALUES( 8,  223, 'AC', 'Armed Forces Canada');
INSERT INTO zones VALUES( 9,  223, 'AE', 'Armed Forces Europe');
INSERT INTO zones VALUES( 10,  223, 'AM', 'Armed Forces Middle East');
INSERT INTO zones VALUES( 11,  223, 'AP', 'Armed Forces Pacific');
INSERT INTO zones VALUES( 12,  223, 'CA', 'California');
INSERT INTO zones VALUES( 13,  223, 'CO', 'Colorado');
INSERT INTO zones VALUES( 14,  223, 'CT', 'Connecticut');
INSERT INTO zones VALUES( 15,  223, 'DE', 'Delaware');
INSERT INTO zones VALUES( 16,  223, 'DC', 'District of Columbia');
INSERT INTO zones VALUES( 17,  223, 'FM', 'Federated States Of Micronesia');
INSERT INTO zones VALUES( 18,  223, 'FL', 'Florida');
INSERT INTO zones VALUES( 19,  223, 'GA', 'Georgia');
INSERT INTO zones VALUES( 20,  223, 'GU', 'Guam');
INSERT INTO zones VALUES( 21,  223, 'HI', 'Hawaii');
INSERT INTO zones VALUES( 22,  223, 'ID', 'Idaho');
INSERT INTO zones VALUES( 23,  223, 'IL', 'Illinois');
INSERT INTO zones VALUES( 24,  223, 'IN', 'Indiana');
INSERT INTO zones VALUES( 25,  223, 'IA', 'Iowa');
INSERT INTO zones VALUES( 26,  223, 'KS', 'Kansas');
INSERT INTO zones VALUES( 27,  223, 'KY', 'Kentucky');
INSERT INTO zones VALUES( 28,  223, 'LA', 'Louisiana');
INSERT INTO zones VALUES( 29,  223, 'ME', 'Maine');
INSERT INTO zones VALUES( 30,  223, 'MH', 'Marshall Islands');
INSERT INTO zones VALUES( 31,  223, 'MD', 'Maryland');
INSERT INTO zones VALUES( 32,  223, 'MA', 'Massachusetts');
INSERT INTO zones VALUES( 33,  223, 'MI', 'Michigan');
INSERT INTO zones VALUES( 34,  223, 'MN', 'Minnesota');
INSERT INTO zones VALUES( 35,  223, 'MS', 'Mississippi');
INSERT INTO zones VALUES( 36,  223, 'MO', 'Missouri');
INSERT INTO zones VALUES( 37,  223, 'MT', 'Montana');
INSERT INTO zones VALUES( 38,  223, 'NE', 'Nebraska');
INSERT INTO zones VALUES( 39,  223, 'NV', 'Nevada');
INSERT INTO zones VALUES( 40,  223, 'NH', 'New Hampshire');
INSERT INTO zones VALUES( 41,  223, 'NJ', 'New Jersey');
INSERT INTO zones VALUES( 42,  223, 'NM', 'New Mexico');
INSERT INTO zones VALUES( 43,  223, 'NY', 'New York');
INSERT INTO zones VALUES( 44,  223, 'NC', 'North Carolina');
INSERT INTO zones VALUES( 45,  223, 'ND', 'North Dakota');
INSERT INTO zones VALUES( 46,  223, 'MP', 'Northern Mariana Islands');
INSERT INTO zones VALUES( 47,  223, 'OH', 'Ohio');
INSERT INTO zones VALUES( 48,  223, 'OK', 'Oklahoma');
INSERT INTO zones VALUES( 49,  223, 'OR', 'Oregon');
INSERT INTO zones VALUES( 50,  223, 'PW', 'Palau');
INSERT INTO zones VALUES( 51,  223, 'PA', 'Pennsylvania');
INSERT INTO zones VALUES( 52,  223, 'PR', 'Puerto Rico');
INSERT INTO zones VALUES( 53,  223, 'RI', 'Rhode Island');
INSERT INTO zones VALUES( 54,  223, 'SC', 'South Carolina');
INSERT INTO zones VALUES( 55,  223, 'SD', 'South Dakota');
INSERT INTO zones VALUES( 56,  223, 'TN', 'Tennessee');
INSERT INTO zones VALUES( 57,  223, 'TX', 'Texas');
INSERT INTO zones VALUES( 58,  223, 'UT', 'Utah');
INSERT INTO zones VALUES( 59,  223, 'VT', 'Vermont');
INSERT INTO zones VALUES( 60,  223, 'VI', 'Virgin Islands');
INSERT INTO zones VALUES( 61,  223, 'VA', 'Virginia');
INSERT INTO zones VALUES( 62,  223, 'WA', 'Washington');
INSERT INTO zones VALUES( 63,  223, 'WV', 'West Virginia');
INSERT INTO zones VALUES( 64,  223, 'WI', 'Wisconsin');
INSERT INTO zones VALUES( 65,  223, 'WY', 'Wyoming');
INSERT INTO zones VALUES( 66,  38, 'AB', 'Alberta');
INSERT INTO zones VALUES( 67,  38, 'BC', 'British Columbia');
INSERT INTO zones VALUES( 68,  38, 'MB', 'Manitoba');
INSERT INTO zones VALUES( 69,  38, 'NF', 'Newfoundland');
INSERT INTO zones VALUES( 70,  38, 'NB', 'New Brunswick');
INSERT INTO zones VALUES( 71,  38, 'NS', 'Nova Scotia');
INSERT INTO zones VALUES( 72,  38, 'NT', 'Northwest Territories');
INSERT INTO zones VALUES( 73,  38, 'NU', 'Nunavut');
INSERT INTO zones VALUES( 74,  38, 'ON', 'Ontario');
INSERT INTO zones VALUES( 75,  38, 'PE', 'Prince Edward Island');
INSERT INTO zones VALUES( 76,  38, 'QC', 'Quebec');
INSERT INTO zones VALUES( 77,  38, 'SK', 'Saskatchewan');
INSERT INTO zones VALUES( 78,  38, 'YT', 'Yukon Territory');
INSERT INTO zones VALUES( 79,  81, 'NDS', 'Niedersachsen');
INSERT INTO zones VALUES( 80,  81, 'BAW', 'Baden-W&uuml;rttemberg');
INSERT INTO zones VALUES( 81,  81, 'BAY', 'Bayern');
INSERT INTO zones VALUES( 82,  81, 'BER', 'Berlin');
INSERT INTO zones VALUES( 83,  81, 'BRG', 'Brandenburg');
INSERT INTO zones VALUES( 84,  81, 'BRE', 'Bremen');
INSERT INTO zones VALUES( 85,  81, 'HAM', 'Hamburg');
INSERT INTO zones VALUES( 86,  81, 'HES', 'Hessen');
INSERT INTO zones VALUES( 87,  81, 'MEC', 'Mecklenburg-Vorpommern');
INSERT INTO zones VALUES( 88,  81, 'NRW', 'Nordrhein-Westfalen');
INSERT INTO zones VALUES( 89,  81, 'RHE', 'Rheinland-Pfalz');
INSERT INTO zones VALUES( 90,  81, 'SAR', 'Saarland');
INSERT INTO zones VALUES( 91,  81, 'SAS', 'Sachsen');
INSERT INTO zones VALUES( 92,  81, 'SAC', 'Sachsen-Anhalt');
INSERT INTO zones VALUES( 93,  81, 'SCN', 'Schleswig-Holstein');
INSERT INTO zones VALUES( 94,  81, 'THE', 'Th&uuml;ringen');
INSERT INTO zones VALUES( 95,  14, 'WI', 'Wien');
INSERT INTO zones VALUES( 96,  14, 'NO', 'Nieder&ouml;sterreich');
INSERT INTO zones VALUES( 97,  14, 'OO', 'Ober&ouml;sterreich');
INSERT INTO zones VALUES( 98,  14, 'SB', 'Salzburg');
INSERT INTO zones VALUES( 99,  14, 'KN', 'K&auml;rnten');
INSERT INTO zones VALUES( 100,  14, 'ST', 'Steiermark');
INSERT INTO zones VALUES( 101,  14, 'TI', 'Tirol');
INSERT INTO zones VALUES( 102,  14, 'BL', 'Burgenland');
INSERT INTO zones VALUES( 103,  14, 'VB', 'Voralberg');
INSERT INTO zones VALUES( 104,  204, 'AG', 'Aargau');
INSERT INTO zones VALUES( 105,  204, 'AI', 'Appenzell Innerrhoden');
INSERT INTO zones VALUES( 106,  204, 'AR', 'Appenzell Ausserrhoden');
INSERT INTO zones VALUES( 107,  204, 'BE', 'Bern');
INSERT INTO zones VALUES( 108,  204, 'BL', 'Basel-Landschaft');
INSERT INTO zones VALUES( 109,  204, 'BS', 'Basel-Stadt');
INSERT INTO zones VALUES( 110,  204, 'FR', 'Freiburg');
INSERT INTO zones VALUES( 111,  204, 'GE', 'Genf');
INSERT INTO zones VALUES( 112,  204, 'GL', 'Glarus');
INSERT INTO zones VALUES( 113,  204, 'JU', 'Graub&uuml;nden');
INSERT INTO zones VALUES( 114,  204, 'JU', 'Jura');
INSERT INTO zones VALUES( 115,  204, 'LU', 'Luzern');
INSERT INTO zones VALUES( 116,  204, 'NE', 'Neuenburg');
INSERT INTO zones VALUES( 117,  204, 'NW', 'Nidwalden');
INSERT INTO zones VALUES( 118,  204, 'OW', 'Obwalden');
INSERT INTO zones VALUES( 119,  204, 'SG', 'St. Gallen');
INSERT INTO zones VALUES( 120,  204, 'SH', 'Schaffhausen');
INSERT INTO zones VALUES( 121,  204, 'SO', 'Solothurn');
INSERT INTO zones VALUES( 122,  204, 'SZ', 'Schwyz');
INSERT INTO zones VALUES( 123,  204, 'TG', 'Thurgau');
INSERT INTO zones VALUES( 124,  204, 'TI', 'Tessin');
INSERT INTO zones VALUES( 125,  204, 'UR', 'Uri');
INSERT INTO zones VALUES( 126,  204, 'VD', 'Waadt');
INSERT INTO zones VALUES( 127,  204, 'VS', 'Wallis');
INSERT INTO zones VALUES( 128,  204, 'ZG', 'Zug');
INSERT INTO zones VALUES( 129,  204, 'ZH', 'Z&uuml;rich');
INSERT INTO zones VALUES( 130,  195, 'A Coru?a', 'A Coru&ntilde;a');
INSERT INTO zones VALUES( 131,  195, 'Alava', 'Alava');
INSERT INTO zones VALUES( 132,  195, 'Albacete', 'Albacete');
INSERT INTO zones VALUES( 133,  195, 'Alicante', 'Alicante');
INSERT INTO zones VALUES( 134,  195, 'Almeria', 'Almeria');
INSERT INTO zones VALUES( 135,  195, 'Asturias', 'Asturias');
INSERT INTO zones VALUES( 136,  195, 'Avila', 'Avila');
INSERT INTO zones VALUES( 137,  195, 'Badajoz', 'Badajoz');
INSERT INTO zones VALUES( 138,  195, 'Baleares', 'Baleares');
INSERT INTO zones VALUES( 139,  195, 'Barcelona', 'Barcelona');
INSERT INTO zones VALUES( 140,  195, 'Burgos', 'Burgos');
INSERT INTO zones VALUES( 141,  195, 'Caceres', 'Caceres');
INSERT INTO zones VALUES( 142,  195, 'Cadiz', 'Cadiz');
INSERT INTO zones VALUES( 143,  195, 'Cantabria', 'Cantabria');
INSERT INTO zones VALUES( 144,  195, 'Castellon', 'Castellon');
INSERT INTO zones VALUES( 145,  195, 'Ceuta', 'Ceuta');
INSERT INTO zones VALUES( 146,  195, 'Ciudad Real', 'Ciudad Real');
INSERT INTO zones VALUES( 147,  195, 'Cordoba', 'Cordoba');
INSERT INTO zones VALUES( 148,  195, 'Cuenca', 'Cuenca');
INSERT INTO zones VALUES( 149,  195, 'Girona', 'Girona');
INSERT INTO zones VALUES( 150,  195, 'Granada', 'Granada');
INSERT INTO zones VALUES( 151,  195, 'Guadalajara', 'Guadalajara');
INSERT INTO zones VALUES( 152,  195, 'Guipuzcoa', 'Guipuzcoa');
INSERT INTO zones VALUES( 153,  195, 'Huelva', 'Huelva');
INSERT INTO zones VALUES( 154,  195, 'Huesca', 'Huesca');
INSERT INTO zones VALUES( 155,  195, 'Jaen', 'Jaen');
INSERT INTO zones VALUES( 156,  195, 'La Rioja', 'La Rioja');
INSERT INTO zones VALUES( 157,  195, 'Las Palmas', 'Las Palmas');
INSERT INTO zones VALUES( 158,  195, 'Leon', 'Leon');
INSERT INTO zones VALUES( 159,  195, 'Lleida', 'Lleida');
INSERT INTO zones VALUES( 160,  195, 'Lugo', 'Lugo');
INSERT INTO zones VALUES( 161,  195, 'Madrid', 'Madrid');
INSERT INTO zones VALUES( 162,  195, 'Malaga', 'Malaga');
INSERT INTO zones VALUES( 163,  195, 'Melilla', 'Melilla');
INSERT INTO zones VALUES( 164,  195, 'Murcia', 'Murcia');
INSERT INTO zones VALUES( 165,  195, 'Navarra', 'Navarra');
INSERT INTO zones VALUES( 166,  195, 'Ourense', 'Ourense');
INSERT INTO zones VALUES( 167,  195, 'Palencia', 'Palencia');
INSERT INTO zones VALUES( 168,  195, 'Pontevedra', 'Pontevedra');
INSERT INTO zones VALUES( 169,  195, 'Salamanca', 'Salamanca');
INSERT INTO zones VALUES( 170,  195, 'Santa Cruz de Tenerife', 'Santa Cruz de Tenerife');
INSERT INTO zones VALUES( 171,  195, 'Segovia', 'Segovia');
INSERT INTO zones VALUES( 172,  195, 'Sevilla', 'Sevilla');
INSERT INTO zones VALUES( 173,  195, 'Soria', 'Soria');
INSERT INTO zones VALUES( 174,  195, 'Tarragona', 'Tarragona');
INSERT INTO zones VALUES( 175,  195, 'Teruel', 'Teruel');
INSERT INTO zones VALUES( 176,  195, 'Toledo', 'Toledo');
INSERT INTO zones VALUES( 177,  195, 'Valencia', 'Valencia');
INSERT INTO zones VALUES( 178,  195, 'Valladolid', 'Valladolid');
INSERT INTO zones VALUES( 179,  195, 'Vizcaya', 'Vizcaya');
INSERT INTO zones VALUES( 180,  195, 'Zamora', 'Zamora');
INSERT INTO zones VALUES( 181,  195, 'Zaragoza', 'Zaragoza');
INSERT INTO zones VALUES( 182,  222, 'ALD', 'Alderney');
INSERT INTO zones VALUES( 183,  222, 'ANT', 'County Antrim');
INSERT INTO zones VALUES( 184,  222, 'ARM', 'County Armagh');
INSERT INTO zones VALUES( 185,  222, 'BSTL', 'Bristol');
INSERT INTO zones VALUES( 186,  222, 'BEDS', 'Bedfordshire');
INSERT INTO zones VALUES( 187,  222, 'BERK', 'Berkshire');
INSERT INTO zones VALUES( 188,  222, 'WMID', 'West Midlands');
INSERT INTO zones VALUES( 189,  222, 'BLGW', 'Blaenau Gwent');
INSERT INTO zones VALUES( 190,  222, 'BORD', 'Borders');
INSERT INTO zones VALUES( 191,  222, 'BRID', 'Bridgend');
INSERT INTO zones VALUES( 192,  222, 'BUCK', 'Buckinghamshire');
INSERT INTO zones VALUES( 193,  222, 'CAER', 'Caerphilly');
INSERT INTO zones VALUES( 194,  222, 'CAIT', 'Caithness');
INSERT INTO zones VALUES( 195,  222, 'CAMB', 'Cambridgeshire');
INSERT INTO zones VALUES( 196,  222, 'CARD', 'Cardiff');
INSERT INTO zones VALUES( 197,  222, 'CARM', 'Carmarthenshire');
INSERT INTO zones VALUES( 198,  222, 'CENT', 'Central');
INSERT INTO zones VALUES( 199,  222, 'CERE', 'Ceredigion');
INSERT INTO zones VALUES( 200,  222, 'CHES', 'Cheshire');
INSERT INTO zones VALUES( 201,  222, 'CHI', 'Channel Islands');
INSERT INTO zones VALUES( 202,  222, 'CLWY', 'Clwyd');
INSERT INTO zones VALUES( 203,  222, 'CONW', 'Conway');
INSERT INTO zones VALUES( 204,  222, 'CORN', 'Cornwall');
INSERT INTO zones VALUES( 205,  222, 'CUMB', 'Cumbria');
INSERT INTO zones VALUES( 206,  222, 'DENB', 'Denbighshire');
INSERT INTO zones VALUES( 207,  222, 'DERB', 'Derbyshire');
INSERT INTO zones VALUES( 208,  222, 'DEVO', 'Devon');
INSERT INTO zones VALUES( 209,  222, 'DORS', 'Dorset');
INSERT INTO zones VALUES( 210,  222, 'DOW', 'County Down');
INSERT INTO zones VALUES( 211,  222, 'DUMF', 'Dumfries & Galloway');
INSERT INTO zones VALUES( 212,  222, 'DURH', 'County Durham');
INSERT INTO zones VALUES( 213,  222, 'DYFE', 'Dyfed');
INSERT INTO zones VALUES( 214,  222, 'ESSE', 'Essex');
INSERT INTO zones VALUES( 215,  222, 'ESUS', 'East Sussex');
INSERT INTO zones VALUES( 216,  222, 'FER', 'Fermanagh');
INSERT INTO zones VALUES( 217,  222, 'FIFE', 'Fife');
INSERT INTO zones VALUES( 218,  222, 'FLIN', 'Flintshire');
INSERT INTO zones VALUES( 219,  222, 'GLAM', 'Glamorgan');
INSERT INTO zones VALUES( 220,  222, 'GLOU', 'Gloucestershire');
INSERT INTO zones VALUES( 221,  222, 'GRAM', 'Grampian');
INSERT INTO zones VALUES( 222,  222, 'GSY', 'Guernsey');
INSERT INTO zones VALUES( 223,  222, 'GWEN', 'Gwent');
INSERT INTO zones VALUES( 224,  222, 'GWYN', 'Gwynedd');
INSERT INTO zones VALUES( 225,  222, 'HAMP', 'Hampshire');
INSERT INTO zones VALUES( 226,  222, 'HERE', 'Herefordshire');
INSERT INTO zones VALUES( 227,  222, 'HERT', 'Hertfordshire');
INSERT INTO zones VALUES( 228,  222, 'EYOR', 'East Riding of Yorkshire');
INSERT INTO zones VALUES( 229,  222, 'IOAN', 'Isle of Anglesey');
INSERT INTO zones VALUES( 230,  222, 'IOMN', 'Isle of Man');
INSERT INTO zones VALUES( 231,  222, 'IOWT', 'Isle of Wight');
INSERT INTO zones VALUES( 232,  222, 'JSY', 'Jersey');
INSERT INTO zones VALUES( 233,  222, 'KENT', 'Kent');
INSERT INTO zones VALUES( 234,  222, 'LANC', 'Lancashire');
INSERT INTO zones VALUES( 235,  222, 'LDY', 'Londonderry');
INSERT INTO zones VALUES( 236,  222, 'LEIC', 'Leicestershire');
INSERT INTO zones VALUES( 237,  222, 'LINC', 'Lincolnshire');
INSERT INTO zones VALUES( 238,  222, 'LOND', 'London');
INSERT INTO zones VALUES( 239,  222, 'LOTH', 'Lothian');
INSERT INTO zones VALUES( 240,  222, 'MANC', 'Manchester');
INSERT INTO zones VALUES( 241,  222, 'MERS', 'Merseyside');
INSERT INTO zones VALUES( 242,  222, 'MDSX', 'Middlesex');
INSERT INTO zones VALUES( 243,  222, 'MERT', 'Merthyr Tydfil');
INSERT INTO zones VALUES( 244,  222, 'MONM', 'Monmouthshire');
INSERT INTO zones VALUES( 245,  222, 'NEAT', 'Neath Port Talbot');
INSERT INTO zones VALUES( 246,  222, 'NEWP', 'Newport');
INSERT INTO zones VALUES( 247,  222, 'NHAM', 'Northamptonshire');
INSERT INTO zones VALUES( 248,  222, 'NORF', 'Norfolk');
INSERT INTO zones VALUES( 249,  222, 'NOTT', 'Nottinghamshire');
INSERT INTO zones VALUES( 250,  222, 'NUMB', 'Northumberland');
INSERT INTO zones VALUES( 251,  222, 'NWHI', 'North west Highlands');
INSERT INTO zones VALUES( 252,  222, 'NYOR', 'North Yorkshire');
INSERT INTO zones VALUES( 253,  222, 'OXFO', 'Oxfordshire');
INSERT INTO zones VALUES( 254,  222, 'PEMB', 'Pembrokeshire');
INSERT INTO zones VALUES( 255,  222, 'POWY', 'Powys');
INSERT INTO zones VALUES( 256,  222, 'SHRO', 'Shropshire');
INSERT INTO zones VALUES( 257,  222, 'SOME', 'Somerset');
INSERT INTO zones VALUES( 258,  222, 'STAF', 'Staffordshire');
INSERT INTO zones VALUES( 259,  222, 'STRA', 'Strathclyde');
INSERT INTO zones VALUES( 260,  222, 'SUFF', 'Suffolk');
INSERT INTO zones VALUES( 261,  222, 'SURR', 'Surrey');
INSERT INTO zones VALUES( 262,  222, 'SWAN', 'Swansea');
INSERT INTO zones VALUES( 263,  222, 'SYOR', 'South Yorkshire');
INSERT INTO zones VALUES( 264,  222, 'SAYR', 'South Ayrshire');
INSERT INTO zones VALUES( 265,  222, 'TAFF', 'Rhondda Cynon Taff');
INSERT INTO zones VALUES( 266,  222, 'TAYS', 'Tayside');
INSERT INTO zones VALUES( 267,  222, 'TORF', 'Torfaen');
INSERT INTO zones VALUES( 268,  222, 'TYR', 'County Tyrone');
INSERT INTO zones VALUES( 269,  222, 'TYWE', 'Tyne & Wear');
INSERT INTO zones VALUES( 270,  222, 'VALE', 'Vale of Glamorgan');
INSERT INTO zones VALUES( 271,  222, 'WORC', 'Worcestershire');
INSERT INTO zones VALUES( 272,  222, 'WARW', 'Warwickshire');
INSERT INTO zones VALUES( 273,  222, 'WILT', 'Wiltshire');
INSERT INTO zones VALUES( 274,  222, 'WISL', 'West Isles');
INSERT INTO zones VALUES( 275,  222, 'WREX', 'Wrexham');
INSERT INTO zones VALUES( 276,  222, 'WSUS', 'West Sussex');
INSERT INTO zones VALUES( 277,  222, 'WYOR', 'West Yorkshire');
INSERT INTO zones VALUES( 278,  153, 'Akaroa', 'Akaroa');
INSERT INTO zones VALUES( 279,  153, 'Albert', 'Albert');
INSERT INTO zones VALUES( 280,  153, 'Albury', 'Albury');
INSERT INTO zones VALUES( 281,  153, 'Alexandra', 'Alexandra');
INSERT INTO zones VALUES( 282,  153, 'Amberley', 'Amberley');
INSERT INTO zones VALUES( 283,  153, 'Arrowtown', 'Arrowtown');
INSERT INTO zones VALUES( 284,  153, 'Ashburton', 'Ashburton');
INSERT INTO zones VALUES( 285,  153, 'Auckland', 'Auckland');
INSERT INTO zones VALUES( 286,  153, 'Balclutha', 'Balclutha');
INSERT INTO zones VALUES( 287,  153, 'Balfour', 'Balfour');
INSERT INTO zones VALUES( 288,  153, 'Beachlands', 'Beachlands');
INSERT INTO zones VALUES( 289,  153, 'Beaumont', 'Beaumont');
INSERT INTO zones VALUES( 290,  153, 'Blackball', 'Blackball');
INSERT INTO zones VALUES( 291,  153, 'Blenheim', 'Blenheim');
INSERT INTO zones VALUES( 292,  153, 'Bluff', 'Bluff');
INSERT INTO zones VALUES( 293,  153, 'Brighton', 'Brighton');
INSERT INTO zones VALUES( 294,  153, 'Brightwater', 'Brightwater');
INSERT INTO zones VALUES( 295,  153, 'Bulls', 'Bulls');
INSERT INTO zones VALUES( 296,  153, 'Cambridge', 'Cambridge');
INSERT INTO zones VALUES( 297,  153, 'Carterton', 'Carterton');
INSERT INTO zones VALUES( 298,  153, 'Cheviot', 'Cheviot');
INSERT INTO zones VALUES( 299,  153, 'Christchurch', 'Christchurch');
INSERT INTO zones VALUES( 300,  153, 'Clarksville', 'Clarksville');
INSERT INTO zones VALUES( 301,  153, 'Coromandel', 'Coromandel');
INSERT INTO zones VALUES( 302,  153, 'Cromwell', 'Cromwell');
INSERT INTO zones VALUES( 303,  153, 'Dannevirke', 'Dannevirke');
INSERT INTO zones VALUES( 304,  153, 'Darfield', 'Darfield');
INSERT INTO zones VALUES( 305,  153, 'Dargaville', 'Dargaville');
INSERT INTO zones VALUES( 306,  153, 'Drury', 'Drury');
INSERT INTO zones VALUES( 307,  153, 'Dunedin', 'Dunedin');
INSERT INTO zones VALUES( 308,  153, 'Duntroon', 'Duntroon');
INSERT INTO zones VALUES( 309,  153, 'Edgecumbe', 'Edgecumbe');
INSERT INTO zones VALUES( 310,  153, 'Eltham', 'Eltham');
INSERT INTO zones VALUES( 311,  153, 'Eketahuna', 'Eketahuna');
INSERT INTO zones VALUES( 312,  153, 'Fairlie', 'Fairlie');
INSERT INTO zones VALUES( 313,  153, 'Featherston', 'Featherston');
INSERT INTO zones VALUES( 314,  153, 'Feilding', 'Feilding');
INSERT INTO zones VALUES( 315,  153, 'Flaxmere', 'Flaxmere');
INSERT INTO zones VALUES( 316,  153, 'Foxton', 'Foxton');
INSERT INTO zones VALUES( 317,  153, 'Foxton Beach', 'Foxton Beach');
INSERT INTO zones VALUES( 318,  153, 'Frankton, Otago', 'Frankton, Otago');
INSERT INTO zones VALUES( 319,  153, 'Frankton, Waikato', 'Frankton, Waikato');
INSERT INTO zones VALUES( 320,  153, 'Franz Josef', 'Franz Josef');
INSERT INTO zones VALUES( 321,  153, 'Geraldine', 'Geraldine');
INSERT INTO zones VALUES( 322,  153, 'Gisborne', 'Gisborne');
INSERT INTO zones VALUES( 323,  153, 'Glenorchy', 'Glenorchy');
INSERT INTO zones VALUES( 324,  153, 'Gore', 'Gore');
INSERT INTO zones VALUES( 325,  153, 'Granity', 'Granity');
INSERT INTO zones VALUES( 326,  153, 'Greymouth', 'Greymouth');
INSERT INTO zones VALUES( 327,  153, 'Greytown', 'Greytown');
INSERT INTO zones VALUES( 328,  153, 'Haast', 'Haast');
INSERT INTO zones VALUES( 329,  153, 'Hakataramea', 'Hakataramea');
INSERT INTO zones VALUES( 330,  153, 'Hamilton', 'Hamilton');
INSERT INTO zones VALUES( 331,  153, 'Hanmer Springs', 'Hanmer Springs');
INSERT INTO zones VALUES( 332,  153, 'Hastings', 'Hastings');
INSERT INTO zones VALUES( 333,  153, 'Havelock', 'Havelock');
INSERT INTO zones VALUES( 334,  153, 'Havelock North', 'Havelock North');
INSERT INTO zones VALUES( 335,  153, 'Hawea', 'Hawea');
INSERT INTO zones VALUES( 336,  153, 'Hawera', 'Hawera');
INSERT INTO zones VALUES( 337,  153, 'Helensville', 'Helensville');
INSERT INTO zones VALUES( 338,  153, 'Henley', 'Henley');
INSERT INTO zones VALUES( 339,  153, 'Hinuera', 'Hinuera');
INSERT INTO zones VALUES( 340,  153, 'Hokitika', 'Hokitika');
INSERT INTO zones VALUES( 341,  153, 'Howick', 'Howick');
INSERT INTO zones VALUES( 342,  153, 'Huntly', 'Huntly');
INSERT INTO zones VALUES( 343,  153, 'Inangahua Junction', 'Inangahua Junction');
INSERT INTO zones VALUES( 344,  153, 'Inglewood', 'Inglewood');
INSERT INTO zones VALUES( 345,  153, 'Invercargill', 'Invercargill');
INSERT INTO zones VALUES( 346,  153, 'Kaiapoi', 'Kaiapoi');
INSERT INTO zones VALUES( 347,  153, 'Kaikohe', 'Kaikohe');
INSERT INTO zones VALUES( 348,  153, 'Kaikoura', 'Kaikoura');
INSERT INTO zones VALUES( 349,  153, 'Kaitaia', 'Kaitaia');
INSERT INTO zones VALUES( 350,  153, 'Kaitangata', 'Kaitangata');
INSERT INTO zones VALUES( 351,  153, 'Karamea', 'Karamea');
INSERT INTO zones VALUES( 352,  153, 'Katikati', 'Katikati');
INSERT INTO zones VALUES( 353,  153, 'Kawakawa', 'Kawakawa');
INSERT INTO zones VALUES( 354,  153, 'Kawerau', 'Kawerau');
INSERT INTO zones VALUES( 355,  153, 'Kerikeri', 'Kerikeri');
INSERT INTO zones VALUES( 356,  153, 'Kihikihi', 'Kihikihi');
INSERT INTO zones VALUES( 357,  153, 'Kinloch', 'Kinloch');
INSERT INTO zones VALUES( 358,  153, 'Kumara', 'Kumara');
INSERT INTO zones VALUES( 359,  153, 'Kumeu', 'Kumeu');
INSERT INTO zones VALUES( 360,  153, 'Kurow', 'Kurow');
INSERT INTO zones VALUES( 361,  153, 'Kawhia', 'Kawhia');
INSERT INTO zones VALUES( 362,  153, 'King Country', 'King Country');
INSERT INTO zones VALUES( 363,  153, 'Lawrence', 'Lawrence');
INSERT INTO zones VALUES( 364,  153, 'Leeston', 'Leeston');
INSERT INTO zones VALUES( 365,  153, 'Leigh', 'Leigh');
INSERT INTO zones VALUES( 366,  153, 'Levin', 'Levin');
INSERT INTO zones VALUES( 367,  153, 'Lincoln', 'Lincoln');
INSERT INTO zones VALUES( 368,  153, 'Little River', 'Little River');
INSERT INTO zones VALUES( 369,  153, 'Lower Hutt', 'Lower Hutt');
INSERT INTO zones VALUES( 370,  153, 'Lumsden', 'Lumsden');
INSERT INTO zones VALUES( 371,  153, 'Lyttelton', 'Lyttelton');
INSERT INTO zones VALUES( 372,  153, 'Manaia', 'Manaia');
INSERT INTO zones VALUES( 373,  153, 'Mangakino', 'Mangakino');
INSERT INTO zones VALUES( 374,  153, 'Manukau', 'Manukau');
INSERT INTO zones VALUES( 375,  153, 'Maraetai', 'Maraetai');
INSERT INTO zones VALUES( 376,  153, 'Martinborough', 'Martinborough');
INSERT INTO zones VALUES( 377,  153, 'Marton', 'Marton');
INSERT INTO zones VALUES( 378,  153, 'Masterton', 'Masterton');
INSERT INTO zones VALUES( 379,  153, 'Matamata', 'Matamata');
INSERT INTO zones VALUES( 380,  153, 'Maungaturoto', 'Maungaturoto');
INSERT INTO zones VALUES( 381,  153, 'Mayfield', 'Mayfield');
INSERT INTO zones VALUES( 382,  153, 'Methven', 'Methven');
INSERT INTO zones VALUES( 383,  153, 'Middlemarch', 'Middlemarch');
INSERT INTO zones VALUES( 384,  153, 'Millers Flat', 'Millers Flat');
INSERT INTO zones VALUES( 385,  153, 'Milton', 'Milton');
INSERT INTO zones VALUES( 386,  153, 'Moeraki', 'Moeraki');
INSERT INTO zones VALUES( 387,  153, 'Moerewa', 'Moerewa');
INSERT INTO zones VALUES( 388,  153, 'Mokau', 'Mokau');
INSERT INTO zones VALUES( 389,  153, 'Morrinsville', 'Morrinsville');
INSERT INTO zones VALUES( 390,  153, 'Mosgiel', 'Mosgiel');
INSERT INTO zones VALUES( 391,  153, 'Mossburn', 'Mossburn');
INSERT INTO zones VALUES( 392,  153, 'Motueka', 'Motueka');
INSERT INTO zones VALUES( 393,  153, 'Mount Maunganui', 'Mount Maunganui');
INSERT INTO zones VALUES( 394,  153, 'Mount Somers', 'Mount Somers');
INSERT INTO zones VALUES( 395,  153, 'Murchison', 'Murchison');
INSERT INTO zones VALUES( 396,  153, 'Murupara', 'Murupara');
INSERT INTO zones VALUES( 397,  153, 'Napier', 'Napier');
INSERT INTO zones VALUES( 398,  153, 'Naseby', 'Naseby');
INSERT INTO zones VALUES( 399,  153, 'Nelson', 'Nelson');
INSERT INTO zones VALUES( 400,  153, 'New Brighton', 'New Brighton');
INSERT INTO zones VALUES( 401,  153, 'New Plymouth', 'New Plymouth');
INSERT INTO zones VALUES( 402,  153, 'Ngapara', 'Ngapara');
INSERT INTO zones VALUES( 403,  153, 'Ngaruawahia', 'Ngaruawahia');
INSERT INTO zones VALUES( 404,  153, 'Ngongotaha', 'Ngongotaha');
INSERT INTO zones VALUES( 405,  153, 'North Shore City', 'North Shore City');
INSERT INTO zones VALUES( 406,  153, 'Oakura', 'Oakura');
INSERT INTO zones VALUES( 407,  153, 'Oamaru', 'Oamaru');
INSERT INTO zones VALUES( 408,  153, 'Oban', 'Oban');
INSERT INTO zones VALUES( 409,  153, 'Ohakune', 'Ohakune');
INSERT INTO zones VALUES( 410,  153, 'Ohoka', 'Ohoka');
INSERT INTO zones VALUES( 411,  153, 'Ohope Beach', 'Ohope Beach');
INSERT INTO zones VALUES( 412,  153, 'Ohura', 'Ohura');
INSERT INTO zones VALUES( 413,  153, 'Okato', 'Okato');
INSERT INTO zones VALUES( 414,  153, 'Omokoroa', 'Omokoroa');
INSERT INTO zones VALUES( 415,  153, 'Opotiki', 'Opotiki');
INSERT INTO zones VALUES( 416,  153, 'Opunake', 'Opunake');
INSERT INTO zones VALUES( 417,  153, 'Oratia', 'Oratia');
INSERT INTO zones VALUES( 418,  153, 'Orewa', 'Orewa');
INSERT INTO zones VALUES( 419,  153, 'Otaki', 'Otaki');
INSERT INTO zones VALUES( 420,  153, 'Otakou', 'Otakou');
INSERT INTO zones VALUES( 421,  153, 'Otorohanga', 'Otorohanga');
INSERT INTO zones VALUES( 422,  153, 'Oxford', 'Oxford');
INSERT INTO zones VALUES( 423,  153, 'Paekakariki', 'Paekakariki');
INSERT INTO zones VALUES( 424,  153, 'Paeroa', 'Paeroa');
INSERT INTO zones VALUES( 425,  153, 'Pahiatua', 'Pahiatua');
INSERT INTO zones VALUES( 426,  153, 'Paihia', 'Paihia');
INSERT INTO zones VALUES( 427,  153, 'Palmerston', 'Palmerston');
INSERT INTO zones VALUES( 428,  153, 'Palmerston North', 'Palmerston North');
INSERT INTO zones VALUES( 429,  153, 'Papakura', 'Papakura');
INSERT INTO zones VALUES( 430,  153, 'Papamoa', 'Papamoa');
INSERT INTO zones VALUES( 431,  153, 'Papatoetoe', 'Papatoetoe');
INSERT INTO zones VALUES( 432,  153, 'Paraparaumu', 'Paraparaumu');
INSERT INTO zones VALUES( 433,  153, 'Patea', 'Patea');
INSERT INTO zones VALUES( 434,  153, 'Pauanui', 'Pauanui');
INSERT INTO zones VALUES( 435,  153, 'Pauatahanui', 'Pauatahanui');
INSERT INTO zones VALUES( 436,  153, 'Petone', 'Petone');
INSERT INTO zones VALUES( 437,  153, 'Picton', 'Picton');
INSERT INTO zones VALUES( 438,  153, 'Piopio', 'Piopio');
INSERT INTO zones VALUES( 439,  153, 'Pirongia', 'Pirongia');
INSERT INTO zones VALUES( 440,  153, 'Pleasant Point', 'Pleasant Point');
INSERT INTO zones VALUES( 441,  153, 'Plimmerton', 'Plimmerton');
INSERT INTO zones VALUES( 442,  153, 'Porirua', 'Porirua');
INSERT INTO zones VALUES( 443,  153, 'Port Chalmers', 'Port Chalmers');
INSERT INTO zones VALUES( 444,  153, 'Portobello', 'Portobello');
INSERT INTO zones VALUES( 445,  153, 'Pukekohe', 'Pukekohe');
INSERT INTO zones VALUES( 446,  153, 'Pukerua Bay', 'Pukerua Bay');
INSERT INTO zones VALUES( 447,  153, 'Pukeuri', 'Pukeuri');
INSERT INTO zones VALUES( 448,  153, 'Putaruru', 'Putaruru');
INSERT INTO zones VALUES( 449,  153, 'Queenstown', 'Queenstown');
INSERT INTO zones VALUES( 450,  153, 'Raetihi', 'Raetihi');
INSERT INTO zones VALUES( 451,  153, 'Raglan', 'Raglan');
INSERT INTO zones VALUES( 452,  153, 'Ramarama', 'Ramarama');
INSERT INTO zones VALUES( 453,  153, 'Ranfurly', 'Ranfurly');
INSERT INTO zones VALUES( 454,  153, 'Rangiora', 'Rangiora');
INSERT INTO zones VALUES( 455,  153, 'Raumati', 'Raumati');
INSERT INTO zones VALUES( 456,  153, 'Reefton', 'Reefton');
INSERT INTO zones VALUES( 457,  153, 'Renwick', 'Renwick');
INSERT INTO zones VALUES( 458,  153, 'Richmond', 'Richmond');
INSERT INTO zones VALUES( 459,  153, 'Riverhead', 'Riverhead');
INSERT INTO zones VALUES( 460,  153, 'Riverton', 'Riverton');
INSERT INTO zones VALUES( 461,  153, 'Rolleston', 'Rolleston');
INSERT INTO zones VALUES( 462,  153, 'Ross', 'Ross');
INSERT INTO zones VALUES( 463,  153, 'Rotorua', 'Rotorua');
INSERT INTO zones VALUES( 464,  153, 'Roxburgh', 'Roxburgh');
INSERT INTO zones VALUES( 465,  153, 'Ruatoria', 'Ruatoria');
INSERT INTO zones VALUES( 466,  153, 'Runanga', 'Runanga');
INSERT INTO zones VALUES( 467,  153, 'Russell', 'Russell');
INSERT INTO zones VALUES( 468,  153, 'Sanson', 'Sanson');
INSERT INTO zones VALUES( 469,  153, 'Seddon', 'Seddon');
INSERT INTO zones VALUES( 470,  153, 'Sheffield', 'Sheffield');
INSERT INTO zones VALUES( 471,  153, 'Shannon', 'Shannon');
INSERT INTO zones VALUES( 472,  153, 'Snells Beach', 'Snells Beach');
INSERT INTO zones VALUES( 473,  153, 'Springfield', 'Springfield');
INSERT INTO zones VALUES( 474,  153, 'Stratford', 'Stratford');
INSERT INTO zones VALUES( 475,  153, 'Silverdale', 'Silverdale');
INSERT INTO zones VALUES( 476,  153, 'Taihape', 'Taihape');
INSERT INTO zones VALUES( 477,  153, 'Taipa-Mangonui', 'Taipa-Mangonui');
INSERT INTO zones VALUES( 478,  153, 'Tairua', 'Tairua');
INSERT INTO zones VALUES( 479,  153, 'Takaka', 'Takaka');
INSERT INTO zones VALUES( 480,  153, 'Tapanui', 'Tapanui');
INSERT INTO zones VALUES( 481,  153, 'Taradale', 'Taradale');
INSERT INTO zones VALUES( 482,  153, 'Taumarunui', 'Taumarunui');
INSERT INTO zones VALUES( 483,  153, 'Taupo', 'Taupo');
INSERT INTO zones VALUES( 484,  153, 'Tauranga', 'Tauranga');
INSERT INTO zones VALUES( 485,  153, 'Te Anau', 'Te Anau');
INSERT INTO zones VALUES( 486,  153, 'Te Arai', 'Te Arai');
INSERT INTO zones VALUES( 487,  153, 'Te Aroha', 'Te Aroha');
INSERT INTO zones VALUES( 488,  153, 'Te Awamutu', 'Te Awamutu');
INSERT INTO zones VALUES( 489,  153, 'Te Kuiti', 'Te Kuiti');
INSERT INTO zones VALUES( 490,  153, 'Te Puke', 'Te Puke');
INSERT INTO zones VALUES( 491,  153, 'Temuka', 'Temuka');
INSERT INTO zones VALUES( 492,  153, 'Thames', 'Thames');
INSERT INTO zones VALUES( 493,  153, 'Timaru', 'Timaru');
INSERT INTO zones VALUES( 494,  153, 'Tinwald', 'Tinwald');
INSERT INTO zones VALUES( 495,  153, 'Tirau', 'Tirau');
INSERT INTO zones VALUES( 496,  153, 'Tokarahi', 'Tokarahi');
INSERT INTO zones VALUES( 497,  153, 'Tokoroa', 'Tokoroa');
INSERT INTO zones VALUES( 498,  153, 'Tolaga Bay', 'Tolaga Bay');
INSERT INTO zones VALUES( 499,  153, 'Tuakau', 'Tuakau');
INSERT INTO zones VALUES( 500,  153, 'Turangi', 'Turangi');
INSERT INTO zones VALUES( 501,  153, 'Twizel', 'Twizel');
INSERT INTO zones VALUES( 502,  153, 'Upper Hutt', 'Upper Hutt');
INSERT INTO zones VALUES( 503,  153, 'Waiheke Island', 'Waiheke Island');
INSERT INTO zones VALUES( 504,  153, 'Waharoa', 'Waharoa');
INSERT INTO zones VALUES( 505,  153, 'Waihi', 'Waihi');
INSERT INTO zones VALUES( 506,  153, 'Waihi Beach', 'Waihi Beach');
INSERT INTO zones VALUES( 507,  153, 'Waikanae', 'Waikanae');
INSERT INTO zones VALUES( 508,  153, 'Waimate', 'Waimate');
INSERT INTO zones VALUES( 509,  153, 'Waiouru', 'Waiouru');
INSERT INTO zones VALUES( 510,  153, 'Wainuiomata', 'Wainuiomata');
INSERT INTO zones VALUES( 511,  153, 'Waipawa', 'Waipawa');
INSERT INTO zones VALUES( 512,  153, 'Waipukurau', 'Waipukurau');
INSERT INTO zones VALUES( 513,  153, 'Wairakei', 'Wairakei');
INSERT INTO zones VALUES( 514,  153, 'Wairoa', 'Wairoa');
INSERT INTO zones VALUES( 515,  153, 'Waitahuna', 'Waitahuna');
INSERT INTO zones VALUES( 516,  153, 'Waikouaiti', 'Waikouaiti');
INSERT INTO zones VALUES( 517,  153, 'Waitakere', 'Waitakere');
INSERT INTO zones VALUES( 518,  153, 'Waitara', 'Waitara');
INSERT INTO zones VALUES( 519,  153, 'Waitoa', 'Waitoa');
INSERT INTO zones VALUES( 520,  153, 'Waitotara', 'Waitotara');
INSERT INTO zones VALUES( 521,  153, 'Waiuku', 'Waiuku');
INSERT INTO zones VALUES( 522,  153, 'Wakefield', 'Wakefield');
INSERT INTO zones VALUES( 523,  153, 'Wallacetown', 'Wallacetown');
INSERT INTO zones VALUES( 524,  153, 'Walton', 'Walton');
INSERT INTO zones VALUES( 525,  153, 'Waverley', 'Waverley');
INSERT INTO zones VALUES( 526,  153, 'Wanaka', 'Wanaka');
INSERT INTO zones VALUES( 527,  153, 'Wanganui', 'Wanganui');
INSERT INTO zones VALUES( 528,  153, 'Ward', 'Ward');
INSERT INTO zones VALUES( 529,  153, 'Wardville', 'Wardville');
INSERT INTO zones VALUES( 530,  153, 'Warkworth', 'Warkworth');
INSERT INTO zones VALUES( 531,  153, 'Wellington', 'Wellington');
INSERT INTO zones VALUES( 532,  153, 'Wellsford', 'Wellsford');
INSERT INTO zones VALUES( 533,  153, 'Westport', 'Westport');
INSERT INTO zones VALUES( 534,  153, 'Whakatane', 'Whakatane');
INSERT INTO zones VALUES( 535,  153, 'Whakamaru', 'Whakamaru');
INSERT INTO zones VALUES( 536,  153, 'Whangamata', 'Whangamata');
INSERT INTO zones VALUES( 537,  153, 'Whangamomona', 'Whangamomona');
INSERT INTO zones VALUES( 538,  153, 'Whangarei', 'Whangarei');
INSERT INTO zones VALUES( 539,  153, 'Whiritoa', 'Whiritoa');
INSERT INTO zones VALUES( 540,  153, 'Whitford', 'Whitford');
INSERT INTO zones VALUES( 541,  153, 'Whitby', 'Whitby');
INSERT INTO zones VALUES( 542,  153, 'Whitianga', 'Whitianga');
INSERT INTO zones VALUES( 543,  153, 'Willowby', 'Willowby');
INSERT INTO zones VALUES( 544,  153, 'Winscombe', 'Winscombe');
INSERT INTO zones VALUES( 545,  153, 'Winton', 'Winton');
INSERT INTO zones VALUES( 546,  153, 'Woodend', 'Woodend');
INSERT INTO zones VALUES( 547,  153, 'Woodville', 'Woodville');
INSERT INTO zones VALUES( 548,  153, 'Wyndham', 'Wyndham');


#
# Data for table: zones_to_geo_zones
#


